// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetTenantPhase provides a mock function for the type Client
func (_mock *Client) GetTenantPhase(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantPhase")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetTenantPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantPhase'
type Client_GetTenantPhase_Call struct {
	*mock.Call
}

// GetTenantPhase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) GetTenantPhase(ctx interface{}) *Client_GetTenantPhase_Call {
	return &Client_GetTenantPhase_Call{Call: _e.mock.On("GetTenantPhase", ctx)}
}

func (_c *Client_GetTenantPhase_Call) Run(run func(ctx context.Context)) *Client_GetTenantPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(arg0)
	})
	return _c
}

func (_c *Client_GetTenantPhase_Call) Return(phase int, err error) *Client_GetTenantPhase_Call {
	_c.Call.Return(phase, err)
	return _c
}

func (_c *Client_GetTenantPhase_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *Client_GetTenantPhase_Call {
	_c.Call.Return(run)
	return _c
}
