# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: dynatrace-operator
description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
home: https://www.dynatrace.com/
type: application
version: 0.0.0-snapshot
appVersion: 0.0.0-snapshot
kubeVersion: '>=1.25.0-0'
maintainers:
- name: team-kubernetes-operator
  email: team-kubernetes-operator@dynatrace.com
sources:
- https://github.com/Dynatrace/dynatrace-operator
