// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/hostevent"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIClient creates a new instance of APIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIClient {
	mock := &APIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

type APIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *APIClient) EXPECT() *APIClient_Expecter {
	return &APIClient_Expecter{mock: &_m.Mock}
}

// GetEntityIDForIP provides a mock function for the type APIClient
func (_mock *APIClient) GetEntityIDForIP(ctx context.Context, ip string) (string, error) {
	ret := _mock.Called(ctx, ip)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityIDForIP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, ip)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetEntityIDForIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityIDForIP'
type APIClient_GetEntityIDForIP_Call struct {
	*mock.Call
}

// GetEntityIDForIP is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
func (_e *APIClient_Expecter) GetEntityIDForIP(ctx interface{}, ip interface{}) *APIClient_GetEntityIDForIP_Call {
	return &APIClient_GetEntityIDForIP_Call{Call: _e.mock.On("GetEntityIDForIP", ctx, ip)}
}

func (_c *APIClient_GetEntityIDForIP_Call) Run(run func(ctx context.Context, ip string)) *APIClient_GetEntityIDForIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_GetEntityIDForIP_Call) Return(s string, err error) *APIClient_GetEntityIDForIP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *APIClient_GetEntityIDForIP_Call) RunAndReturn(run func(ctx context.Context, ip string) (string, error)) *APIClient_GetEntityIDForIP_Call {
	_c.Call.Return(run)
	return _c
}

// SendEvent provides a mock function for the type APIClient
func (_mock *APIClient) SendEvent(ctx context.Context, event hostevent.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, hostevent.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_SendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEvent'
type APIClient_SendEvent_Call struct {
	*mock.Call
}

// SendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event hostevent.Event
func (_e *APIClient_Expecter) SendEvent(ctx interface{}, event interface{}) *APIClient_SendEvent_Call {
	return &APIClient_SendEvent_Call{Call: _e.mock.On("SendEvent", ctx, event)}
}

func (_c *APIClient_SendEvent_Call) Run(run func(ctx context.Context, event hostevent.Event)) *APIClient_SendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 hostevent.Event
		if args[1] != nil {
			arg1 = args[1].(hostevent.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_SendEvent_Call) Return(err error) *APIClient_SendEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_SendEvent_Call) RunAndReturn(run func(ctx context.Context, event hostevent.Event) error) *APIClient_SendEvent_Call {
	_c.Call.Return(run)
	return _c
}
