// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	registry "github.com/Dynatrace/dynatrace-operator/pkg/oci/registry"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/google/go-containerregistry/pkg/v1"
)

// MockImageGetter is an autogenerated mock type for the ImageGetter type
type MockImageGetter struct {
	mock.Mock
}

type MockImageGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageGetter) EXPECT() *MockImageGetter_Expecter {
	return &MockImageGetter_Expecter{mock: &_m.Mock}
}

// GetImageVersion provides a mock function with given fields: ctx, imageName
func (_m *MockImageGetter) GetImageVersion(ctx context.Context, imageName string) (registry.ImageVersion, error) {
	ret := _m.Called(ctx, imageName)

	if len(ret) == 0 {
		panic("no return value specified for GetImageVersion")
	}

	var r0 registry.ImageVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (registry.ImageVersion, error)); ok {
		return rf(ctx, imageName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) registry.ImageVersion); ok {
		r0 = rf(ctx, imageName)
	} else {
		r0 = ret.Get(0).(registry.ImageVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, imageName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageGetter_GetImageVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageVersion'
type MockImageGetter_GetImageVersion_Call struct {
	*mock.Call
}

// GetImageVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName string
func (_e *MockImageGetter_Expecter) GetImageVersion(ctx interface{}, imageName interface{}) *MockImageGetter_GetImageVersion_Call {
	return &MockImageGetter_GetImageVersion_Call{Call: _e.mock.On("GetImageVersion", ctx, imageName)}
}

func (_c *MockImageGetter_GetImageVersion_Call) Run(run func(ctx context.Context, imageName string)) *MockImageGetter_GetImageVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockImageGetter_GetImageVersion_Call) Return(_a0 registry.ImageVersion, _a1 error) *MockImageGetter_GetImageVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageGetter_GetImageVersion_Call) RunAndReturn(run func(context.Context, string) (registry.ImageVersion, error)) *MockImageGetter_GetImageVersion_Call {
	_c.Call.Return(run)
	return _c
}

// PullImageInfo provides a mock function with given fields: ctx, imageName
func (_m *MockImageGetter) PullImageInfo(ctx context.Context, imageName string) (*v1.Image, error) {
	ret := _m.Called(ctx, imageName)

	if len(ret) == 0 {
		panic("no return value specified for PullImageInfo")
	}

	var r0 *v1.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1.Image, error)); ok {
		return rf(ctx, imageName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.Image); ok {
		r0 = rf(ctx, imageName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, imageName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageGetter_PullImageInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullImageInfo'
type MockImageGetter_PullImageInfo_Call struct {
	*mock.Call
}

// PullImageInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName string
func (_e *MockImageGetter_Expecter) PullImageInfo(ctx interface{}, imageName interface{}) *MockImageGetter_PullImageInfo_Call {
	return &MockImageGetter_PullImageInfo_Call{Call: _e.mock.On("PullImageInfo", ctx, imageName)}
}

func (_c *MockImageGetter_PullImageInfo_Call) Run(run func(ctx context.Context, imageName string)) *MockImageGetter_PullImageInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockImageGetter_PullImageInfo_Call) Return(_a0 *v1.Image, _a1 error) *MockImageGetter_PullImageInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageGetter_PullImageInfo_Call) RunAndReturn(run func(context.Context, string) (*v1.Image, error)) *MockImageGetter_PullImageInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageGetter creates a new instance of MockImageGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageGetter {
	mock := &MockImageGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
