{{- if and .Values.rbac.prometheus.create (.Values.experimental).enablePrometheus }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-prometheus-gateway
  labels:
    {{- include "dynatrace-operator.gatewayLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-prometheus-gateway
subjects:
  - kind: ServiceAccount
    name: dynatrace-prometheus-gateway
    namespace: {{ .Release.Namespace }}
{{- end }}
