{{- if and .Values.rbac.prometheus.create (.Values.experimental).enablePrometheus }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-prometheus-scraper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.scraperLabels" . | nindent 4 }}
{{- end }}
