{{- if .Values.rbac.prometheus.create }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-target-allocator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.targetAllocatorLabels" . | nindent 4 }}
{{- end }}
