// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// NewReconciler creates a new instance of Reconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reconciler {
	mock := &Reconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Reconciler is an autogenerated mock type for the Reconciler type
type Reconciler struct {
	mock.Mock
}

type Reconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *Reconciler) EXPECT() *Reconciler_Expecter {
	return &Reconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type Reconciler
func (_mock *Reconciler) Reconcile(context1 context.Context, request reconcile.Request) (reconcile.Result, error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 reconcile.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, reconcile.Request) (reconcile.Result, error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, reconcile.Request) reconcile.Result); ok {
		r0 = returnFunc(context1, request)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, reconcile.Request) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Reconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type Reconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - context1 context.Context
//   - request reconcile.Request
func (_e *Reconciler_Expecter) Reconcile(context1 interface{}, request interface{}) *Reconciler_Reconcile_Call {
	return &Reconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", context1, request)}
}

func (_c *Reconciler_Reconcile_Call) Run(run func(context1 context.Context, request reconcile.Request)) *Reconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 reconcile.Request
		if args[1] != nil {
			arg1 = args[1].(reconcile.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Reconciler_Reconcile_Call) Return(result reconcile.Result, err error) *Reconciler_Reconcile_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *Reconciler_Reconcile_Call) RunAndReturn(run func(context1 context.Context, request reconcile.Request) (reconcile.Result, error)) *Reconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
