{{- if .Values.rbac.kspm.create }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-node-config-collector
  namespace: {{ .Release.Namespace }}
  {{- if .Values.rbac.kspm.annotations }}
  annotations:
    {{- toYaml .Values.rbac.kspm.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dynatrace-operator.kspmLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{ end }}
