{{ if (include "dynatrace-operator.needCSI" .) }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-oneagent-csi-driver
  labels:
    {{- include "dynatrace-operator.csiLabels" . | nindent 4 }}
rules:
  {{- if (eq (include "dynatrace-operator.platform" .) "openshift") }}
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
  {{ end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-oneagent-csi-driver
  labels:
    {{- include "dynatrace-operator.csiLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: dynatrace-oneagent-csi-driver
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: dynatrace-oneagent-csi-driver
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
