{{ if (include "dynatrace-operator.needCSI" .) }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.oneagent.dynatrace.com
  labels:
    {{- if eq (include "dynatrace-operator.platform" .) "openshift" }}
    security.openshift.io/csi-ephemeral-volume-profile: "restricted"
    {{- end }}
    {{- include "dynatrace-operator.csiLabels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Ephemeral
{{- end -}}
