{{ if (include "dynatrace-operator.needCSI" .) }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-oneagent-csi-driver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.csiLabels" . | nindent 4 }}
{{- end -}}
