{{- if or (and .Values.rbac.extensions.create .Values.rbac.extensions.prometheus.create) (.Values.rbac.telemetryIngest.create) }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-otel-collector
  namespace: {{ .Release.Namespace }}
  {{- if .Values.rbac.extensions.annotations }}
  annotations:
    {{- toYaml .Values.rbac.extensions.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dynatrace-operator.openTelemetryCollectorLabels" . | nindent 4 }}
{{ end }}
