// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dynakube "github.com/Dynatrace/dynatrace-operator/pkg/api/v1beta1/dynakube"

	mock "github.com/stretchr/testify/mock"
)

// Reconciler is an autogenerated mock type for the Reconciler type
type Reconciler struct {
	mock.Mock
}

type Reconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *Reconciler) EXPECT() *Reconciler_Expecter {
	return &Reconciler_Expecter{mock: &_m.Mock}
}

// ReconcileAPIUrl provides a mock function with given fields: ctx, _a1
func (_m *Reconciler) ReconcileAPIUrl(ctx context.Context, _a1 *dynakube.DynaKube) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileAPIUrl")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reconciler_ReconcileAPIUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileAPIUrl'
type Reconciler_ReconcileAPIUrl_Call struct {
	*mock.Call
}

// ReconcileAPIUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *dynakube.DynaKube
func (_e *Reconciler_Expecter) ReconcileAPIUrl(ctx interface{}, _a1 interface{}) *Reconciler_ReconcileAPIUrl_Call {
	return &Reconciler_ReconcileAPIUrl_Call{Call: _e.mock.On("ReconcileAPIUrl", ctx, _a1)}
}

func (_c *Reconciler_ReconcileAPIUrl_Call) Run(run func(ctx context.Context, _a1 *dynakube.DynaKube)) *Reconciler_ReconcileAPIUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dynakube.DynaKube))
	})
	return _c
}

func (_c *Reconciler_ReconcileAPIUrl_Call) Return(_a0 error) *Reconciler_ReconcileAPIUrl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Reconciler_ReconcileAPIUrl_Call) RunAndReturn(run func(context.Context, *dynakube.DynaKube) error) *Reconciler_ReconcileAPIUrl_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileActiveGateCommunicationHosts provides a mock function with given fields: ctx, _a1
func (_m *Reconciler) ReconcileActiveGateCommunicationHosts(ctx context.Context, _a1 *dynakube.DynaKube) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileActiveGateCommunicationHosts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reconciler_ReconcileActiveGateCommunicationHosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileActiveGateCommunicationHosts'
type Reconciler_ReconcileActiveGateCommunicationHosts_Call struct {
	*mock.Call
}

// ReconcileActiveGateCommunicationHosts is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *dynakube.DynaKube
func (_e *Reconciler_Expecter) ReconcileActiveGateCommunicationHosts(ctx interface{}, _a1 interface{}) *Reconciler_ReconcileActiveGateCommunicationHosts_Call {
	return &Reconciler_ReconcileActiveGateCommunicationHosts_Call{Call: _e.mock.On("ReconcileActiveGateCommunicationHosts", ctx, _a1)}
}

func (_c *Reconciler_ReconcileActiveGateCommunicationHosts_Call) Run(run func(ctx context.Context, _a1 *dynakube.DynaKube)) *Reconciler_ReconcileActiveGateCommunicationHosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dynakube.DynaKube))
	})
	return _c
}

func (_c *Reconciler_ReconcileActiveGateCommunicationHosts_Call) Return(_a0 error) *Reconciler_ReconcileActiveGateCommunicationHosts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Reconciler_ReconcileActiveGateCommunicationHosts_Call) RunAndReturn(run func(context.Context, *dynakube.DynaKube) error) *Reconciler_ReconcileActiveGateCommunicationHosts_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileCodeModuleCommunicationHosts provides a mock function with given fields: ctx, _a1
func (_m *Reconciler) ReconcileCodeModuleCommunicationHosts(ctx context.Context, _a1 *dynakube.DynaKube) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileCodeModuleCommunicationHosts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reconciler_ReconcileCodeModuleCommunicationHosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileCodeModuleCommunicationHosts'
type Reconciler_ReconcileCodeModuleCommunicationHosts_Call struct {
	*mock.Call
}

// ReconcileCodeModuleCommunicationHosts is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *dynakube.DynaKube
func (_e *Reconciler_Expecter) ReconcileCodeModuleCommunicationHosts(ctx interface{}, _a1 interface{}) *Reconciler_ReconcileCodeModuleCommunicationHosts_Call {
	return &Reconciler_ReconcileCodeModuleCommunicationHosts_Call{Call: _e.mock.On("ReconcileCodeModuleCommunicationHosts", ctx, _a1)}
}

func (_c *Reconciler_ReconcileCodeModuleCommunicationHosts_Call) Run(run func(ctx context.Context, _a1 *dynakube.DynaKube)) *Reconciler_ReconcileCodeModuleCommunicationHosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dynakube.DynaKube))
	})
	return _c
}

func (_c *Reconciler_ReconcileCodeModuleCommunicationHosts_Call) Return(_a0 error) *Reconciler_ReconcileCodeModuleCommunicationHosts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Reconciler_ReconcileCodeModuleCommunicationHosts_Call) RunAndReturn(run func(context.Context, *dynakube.DynaKube) error) *Reconciler_ReconcileCodeModuleCommunicationHosts_Call {
	_c.Call.Return(run)
	return _c
}

// NewReconciler creates a new instance of Reconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reconciler {
	mock := &Reconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
