// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	webhook "github.com/Dynatrace/dynatrace-operator/pkg/webhook"
	mock "github.com/stretchr/testify/mock"
)

// PodInjector is an autogenerated mock type for the PodInjector type
type PodInjector struct {
	mock.Mock
}

type PodInjector_Expecter struct {
	mock *mock.Mock
}

func (_m *PodInjector) EXPECT() *PodInjector_Expecter {
	return &PodInjector_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *PodInjector) Handle(_a0 context.Context, _a1 *webhook.MutationRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *webhook.MutationRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PodInjector_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type PodInjector_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *webhook.MutationRequest
func (_e *PodInjector_Expecter) Handle(_a0 interface{}, _a1 interface{}) *PodInjector_Handle_Call {
	return &PodInjector_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *PodInjector_Handle_Call) Run(run func(_a0 context.Context, _a1 *webhook.MutationRequest)) *PodInjector_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*webhook.MutationRequest))
	})
	return _c
}

func (_c *PodInjector_Handle_Call) Return(_a0 error) *PodInjector_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PodInjector_Handle_Call) RunAndReturn(run func(context.Context, *webhook.MutationRequest) error) *PodInjector_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewPodInjector creates a new instance of PodInjector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPodInjector(t interface {
	mock.TestingT
	Cleanup(func())
}) *PodInjector {
	mock := &PodInjector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
