{{- if .Values.crdStorageMigrationJob }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-crd-storage-migration
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.crdStorageMigrationLabels" . | nindent 4 }}
  annotations:
    {{- include "dynatrace-operator.helmPreUpgradeHookAnnotations" . | nindent 4 }}
{{- end }}
