{{- if .Values.rbac.extensions.create }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-extension-controller
  labels:
    {{- include "dynatrace-operator.extensionControllerLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - list
      - watch
  {{- if (include "dynatrace-operator.openshiftOrOlm" .) }}
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - nonroot-v2
    resources:
      - securitycontextconstraints
    verbs:
      - use
  {{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-extension-controller
  labels:
    {{- include "dynatrace-operator.extensionControllerLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-extension-controller
subjects:
  - kind: ServiceAccount
    name: dynatrace-extension-controller
    namespace: {{ .Release.Namespace }}
{{ end }}
