{{- if (and .Values.rbac.extensions.prometheus.create .Values.rbac.extensions.create (eq (include "dynatrace-operator.openshiftOrOlm" .) "true")) }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-extension-controller-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.extensionControllerLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-extension-controller-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.extensionControllerLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: dynatrace-extension-controller
roleRef:
  kind: Role
  name: dynatrace-extension-controller-prometheus
  apiGroup: rbac.authorization.k8s.io
{{ end }}
