{{- if .Values.rbac.extensions.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-extension-controller
  namespace: {{ .Release.Namespace }}
  {{- if .Values.rbac.extensions.annotations }}
  annotations:
    {{- toYaml .Values.rbac.extensions.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dynatrace-operator.extensionControllerLabels" . | nindent 4 }}
{{ end }}
