name: Build Helm packages
description: Builds the helm packages
inputs:
  version_without_prefix:
    description: The version of the operator that should be deployed without the leading 'v' character
    required: true
  github-token:
    description: Token used to fetch the current helm version
    required: true
  secring:
    description: Contains the private key that is used to sign the helm packages
    required: true
  passphrase:
    description: Passphrase used to encrypt the private key
    required: true
  output-dir:
    description: Directory where built package should be put
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
      with:
        # renovate datasource=github-releases depName=helm/helm
        version: v4.2.0
        token: ${{ inputs.github-token }}
    - name: Generate helm-package
      shell: bash
      env:
        OUTPUT_DIR: ${{ inputs.output-dir }}
        PASSPHRASE: ${{ inputs.passphrase }}
        SECRING: ${{ inputs.secring }}
        VERSION_WITHOUT_PREFIX: ${{ inputs.version_without_prefix }}
      run: hack/build/ci/generate-helm-package.sh
