// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetScopes provides a mock function for the type Client
func (_mock *Client) GetScopes(ctx context.Context, token string) ([]string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetScopes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScopes'
type Client_GetScopes_Call struct {
	*mock.Call
}

// GetScopes is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Client_Expecter) GetScopes(ctx interface{}, token interface{}) *Client_GetScopes_Call {
	return &Client_GetScopes_Call{Call: _e.mock.On("GetScopes", ctx, token)}
}

func (_c *Client_GetScopes_Call) Run(run func(ctx context.Context, token string)) *Client_GetScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetScopes_Call) Return(strings []string, err error) *Client_GetScopes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Client_GetScopes_Call) RunAndReturn(run func(ctx context.Context, token string) ([]string, error)) *Client_GetScopes_Call {
	_c.Call.Return(run)
	return _c
}
