package consts

const (
	AgCertificate                   = "custom-cas/agcrt.pem"
	AgCertificateAndPrivateKey      = "custom-cas/agcrtkey.p12"
	AgCertificateAndPrivateKeyField = "server.p12"
	AgSecretName                    = "ag-ca"
	TelemetryIngestTLSSecretName    = "telemetry-ingest-tls"
	DevRegistryPullSecretName       = "devregistry"

	DefaultEecImageRepo           = "public.ecr.aws/dynatrace/dynatrace-eec"
	DefaultEecImageTag            = "1.327.30.20251107-111521"
	EecImageRepoEnvVar            = "E2E_EEC_IMAGE_REPO"
	EecImageTagEnvVar             = "E2E_EEC_IMAGE_TAG"
	DefaultLogMonitoringImageRepo = "public.ecr.aws/dynatrace/dynatrace-logmodule"
	DefaultLogMonitoringImageTag  = "1.309.59.20250319-140247"
	LogMonitoringImageRepoEnvVar  = "E2E_LOGMON_IMAGE_REPO"
	LogMonitoringImageTagEnvVar   = "E2E_LOGMON_IMAGE_TAG"
	DefaultKSPMImageRepo          = "public.ecr.aws/dynatrace/dynatrace-k8s-node-config-collector"
	DefaultKSPMImageTag           = "1.5.2"
	KSPMImageRepoEnvVar           = "E2E_KSPM_IMAGE_REPO"
	KSPMImageTagEnvVar            = "E2E_KSPM_IMAGE_TAG"
	DefaultOtelCollectorImageRepo = "public.ecr.aws/dynatrace/dynatrace-otel-collector"
	DefaultOtelCollectorImageTag  = "latest"
	OtelCollectorImageRepoEnvVar  = "E2E_OTELC_IMAGE_REPO"
	OtelCollectorImageTagEnvVar   = "E2E_OTELC_IMAGE_TAG"
	DefaultDBExecutorImageRepo    = "public.ecr.aws/dynatrace/dynatrace-database-datasource-executor"
	DefaultDBExecutorImageTag     = "1.327.41.20251114-153023"
	DBExecutorImageRepoEnvVar     = "E2E_DB_EXECUTOR_IMAGE_REPO"
	DBExecutorImageTagEnvVar      = "E2E_DB_EXECUTOR_IMAGE_TAG"
)
