package validation

const oneagentEnableVolumeStorageEnvVarName = "ONEAGENT_ENABLE_VOLUME_STORAGE"
const oneagentInstallerScriptURLEnvVarName = "ONEAGENT_INSTALLER_SCRIPT_URL"
const oneagentInstallerTokenEnvVarName = "ONEAGENT_INSTALLER_TOKEN"
