// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logmonitoring

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/settings"
	mock "github.com/stretchr/testify/mock"
)

// newMockSubReconciler creates a new instance of mockSubReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSubReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSubReconciler {
	mock := &mockSubReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSubReconciler is an autogenerated mock type for the subReconciler type
type mockSubReconciler struct {
	mock.Mock
}

type mockSubReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSubReconciler) EXPECT() *mockSubReconciler_Expecter {
	return &mockSubReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockSubReconciler
func (_mock *mockSubReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockSubReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockSubReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockSubReconciler_Expecter) Reconcile(ctx interface{}, dk interface{}) *mockSubReconciler_Reconcile_Call {
	return &mockSubReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk)}
}

func (_c *mockSubReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockSubReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockSubReconciler_Reconcile_Call) Return(err error) *mockSubReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockSubReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockSubReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLogmonsettingsSubReconciler creates a new instance of mockLogmonsettingsSubReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLogmonsettingsSubReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLogmonsettingsSubReconciler {
	mock := &mockLogmonsettingsSubReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockLogmonsettingsSubReconciler is an autogenerated mock type for the logmonsettingsSubReconciler type
type mockLogmonsettingsSubReconciler struct {
	mock.Mock
}

type mockLogmonsettingsSubReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLogmonsettingsSubReconciler) EXPECT() *mockLogmonsettingsSubReconciler_Expecter {
	return &mockLogmonsettingsSubReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockLogmonsettingsSubReconciler
func (_mock *mockLogmonsettingsSubReconciler) Reconcile(ctx context.Context, dtClient settings.Client, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dtClient, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, settings.Client, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dtClient, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockLogmonsettingsSubReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockLogmonsettingsSubReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dtClient settings.Client
//   - dk *dynakube.DynaKube
func (_e *mockLogmonsettingsSubReconciler_Expecter) Reconcile(ctx interface{}, dtClient interface{}, dk interface{}) *mockLogmonsettingsSubReconciler_Reconcile_Call {
	return &mockLogmonsettingsSubReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dtClient, dk)}
}

func (_c *mockLogmonsettingsSubReconciler_Reconcile_Call) Run(run func(ctx context.Context, dtClient settings.Client, dk *dynakube.DynaKube)) *mockLogmonsettingsSubReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 settings.Client
		if args[1] != nil {
			arg1 = args[1].(settings.Client)
		}
		var arg2 *dynakube.DynaKube
		if args[2] != nil {
			arg2 = args[2].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockLogmonsettingsSubReconciler_Reconcile_Call) Return(err error) *mockLogmonsettingsSubReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockLogmonsettingsSubReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dtClient settings.Client, dk *dynakube.DynaKube) error) *mockLogmonsettingsSubReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
