# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynatrace-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dynatrace.com
    resources:
      - dynakubes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: dynatrace-webhook
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: dynatrace-webhook
  apiGroup: rbac.authorization.k8s.io
