# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-webhook
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}
spec:
  selector:
  {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: server-port
