# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-webhook
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}

