# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: dynatrace-webhook
  labels:
  {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-dynatrace-com-v1beta5-dynakube
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1beta5
        resources:
          - dynakubes
    name: v1beta5.dynakube.webhook.dynatrace.com
    timeoutSeconds: {{.Values.webhook.validatingWebhook.timeoutSeconds}}
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-dynatrace-com-v1beta6-dynakube
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1beta6
        resources:
          - dynakubes
    name: v1beta6.dynakube.webhook.dynatrace.com
    timeoutSeconds: {{.Values.webhook.validatingWebhook.timeoutSeconds}}
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-dynatrace-com-v1alpha1-edgeconnect
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1alpha1
        resources:
          - edgeconnects
    name: v1alpha1.edgeconnect.webhook.dynatrace.com
    timeoutSeconds: {{.Values.webhook.validatingWebhook.timeoutSeconds}}
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-dynatrace-com-v1alpha2-edgeconnect
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1alpha2
        resources:
          - edgeconnects
    name: v1alpha2.edgeconnect.webhook.dynatrace.com
    timeoutSeconds: {{.Values.webhook.validatingWebhook.timeoutSeconds}}
    sideEffects: None
    matchPolicy: Exact
