// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dynakube

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace"
	mock "github.com/stretchr/testify/mock"
)

// newMockDtclientReconciler creates a new instance of mockDtclientReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDtclientReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDtclientReconciler {
	mock := &mockDtclientReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDtclientReconciler is an autogenerated mock type for the dtclientReconciler type
type mockDtclientReconciler struct {
	mock.Mock
}

type mockDtclientReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDtclientReconciler) EXPECT() *mockDtclientReconciler_Expecter {
	return &mockDtclientReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockDtclientReconciler
func (_mock *mockDtclientReconciler) Reconcile(ctx context.Context, dtclient dynatrace.Client, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dtclient, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dynatrace.Client, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dtclient, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDtclientReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockDtclientReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dtclient dynatrace.Client
//   - dk *dynakube.DynaKube
func (_e *mockDtclientReconciler_Expecter) Reconcile(ctx interface{}, dtclient interface{}, dk interface{}) *mockDtclientReconciler_Reconcile_Call {
	return &mockDtclientReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dtclient, dk)}
}

func (_c *mockDtclientReconciler_Reconcile_Call) Run(run func(ctx context.Context, dtclient dynatrace.Client, dk *dynakube.DynaKube)) *mockDtclientReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dynatrace.Client
		if args[1] != nil {
			arg1 = args[1].(dynatrace.Client)
		}
		var arg2 *dynakube.DynaKube
		if args[2] != nil {
			arg2 = args[2].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDtclientReconciler_Reconcile_Call) Return(err error) *mockDtclientReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDtclientReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dtclient dynatrace.Client, dk *dynakube.DynaKube) error) *mockDtclientReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
