// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/image"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ComponentLatestImageInfo provides a mock function for the type Client
func (_mock *Client) ComponentLatestImageInfo(ctx context.Context, component image.ComponentType, registry string) (*image.Info, error) {
	ret := _mock.Called(ctx, component, registry)

	if len(ret) == 0 {
		panic("no return value specified for ComponentLatestImageInfo")
	}

	var r0 *image.Info
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.ComponentType, string) (*image.Info, error)); ok {
		return returnFunc(ctx, component, registry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.ComponentType, string) *image.Info); ok {
		r0 = returnFunc(ctx, component, registry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.Info)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, image.ComponentType, string) error); ok {
		r1 = returnFunc(ctx, component, registry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_ComponentLatestImageInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComponentLatestImageInfo'
type Client_ComponentLatestImageInfo_Call struct {
	*mock.Call
}

// ComponentLatestImageInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - component image.ComponentType
//   - registry string
func (_e *Client_Expecter) ComponentLatestImageInfo(ctx interface{}, component interface{}, registry interface{}) *Client_ComponentLatestImageInfo_Call {
	return &Client_ComponentLatestImageInfo_Call{Call: _e.mock.On("ComponentLatestImageInfo", ctx, component, registry)}
}

func (_c *Client_ComponentLatestImageInfo_Call) Run(run func(ctx context.Context, component image.ComponentType, registry string)) *Client_ComponentLatestImageInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 image.ComponentType
		if args[1] != nil {
			arg1 = args[1].(image.ComponentType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_ComponentLatestImageInfo_Call) Return(info *image.Info, err error) *Client_ComponentLatestImageInfo_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *Client_ComponentLatestImageInfo_Call) RunAndReturn(run func(ctx context.Context, component image.ComponentType, registry string) (*image.Info, error)) *Client_ComponentLatestImageInfo_Call {
	_c.Call.Return(run)
	return _c
}
