{{- if .Values.rbac.activeGate.create }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-activegate
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.rbac.activeGate.annotations }}
    {{- toYaml .Values.rbac.activeGate.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dynatrace-operator.activegateLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{ end }}
