repositoryID: b0a4eac3-5980-4825-a4d7-77f116e2e6ab
owners:
  - name: 0sewa0
    email: marcell.sevcsik@dynatrace.com
  - name: andriisoldatenko
    email: andrii.soldatenko@dynatrace.com
  - name: geba-dyna
    email: george.balea@dynatrace.com
