// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package capability

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCapabilityReconciler creates a new instance of MockCapabilityReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCapabilityReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCapabilityReconciler {
	mock := &MockCapabilityReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCapabilityReconciler is an autogenerated mock type for the CapabilityReconciler type
type MockCapabilityReconciler struct {
	mock.Mock
}

type MockCapabilityReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCapabilityReconciler) EXPECT() *MockCapabilityReconciler_Expecter {
	return &MockCapabilityReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type MockCapabilityReconciler
func (_mock *MockCapabilityReconciler) Reconcile(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCapabilityReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type MockCapabilityReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCapabilityReconciler_Expecter) Reconcile(ctx interface{}) *MockCapabilityReconciler_Reconcile_Call {
	return &MockCapabilityReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx)}
}

func (_c *MockCapabilityReconciler_Reconcile_Call) Run(run func(ctx context.Context)) *MockCapabilityReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapabilityReconciler_Reconcile_Call) Return(err error) *MockCapabilityReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCapabilityReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context) error) *MockCapabilityReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
