{{ if (include "dynatrace-operator.needAutopilotAllowlisting" .) }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: auto.gke.io/v1
kind: AllowlistSynchronizer
metadata:
  name: dynatrace-operator
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, pre-rollback
spec:
  allowlistPaths:
  - Dynatrace/csidriver/{{ .Chart.AppVersion }}/*
  - Dynatrace/logmonitoring/{{ .Chart.AppVersion }}/*
  - Dynatrace/csijob/{{ .Chart.AppVersion }}/*
{{- end -}}
