# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.operatorLabels" . | nindent 4 }}
