// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/images"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ComponentLatestImageURI provides a mock function for the type Client
func (_mock *Client) ComponentLatestImageURI(ctx context.Context, component images.ComponentType, registry string) (string, error) {
	ret := _mock.Called(ctx, component, registry)

	if len(ret) == 0 {
		panic("no return value specified for ComponentLatestImageURI")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, images.ComponentType, string) (string, error)); ok {
		return returnFunc(ctx, component, registry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, images.ComponentType, string) string); ok {
		r0 = returnFunc(ctx, component, registry)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, images.ComponentType, string) error); ok {
		r1 = returnFunc(ctx, component, registry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_ComponentLatestImageURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComponentLatestImageURI'
type Client_ComponentLatestImageURI_Call struct {
	*mock.Call
}

// ComponentLatestImageURI is a helper method to define mock.On call
//   - ctx context.Context
//   - component images.ComponentType
//   - registry string
func (_e *Client_Expecter) ComponentLatestImageURI(ctx interface{}, component interface{}, registry interface{}) *Client_ComponentLatestImageURI_Call {
	return &Client_ComponentLatestImageURI_Call{Call: _e.mock.On("ComponentLatestImageURI", ctx, component, registry)}
}

func (_c *Client_ComponentLatestImageURI_Call) Run(run func(ctx context.Context, component images.ComponentType, registry string)) *Client_ComponentLatestImageURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 images.ComponentType
		if args[1] != nil {
			arg1 = args[1].(images.ComponentType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_ComponentLatestImageURI_Call) Return(s string, err error) *Client_ComponentLatestImageURI_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_ComponentLatestImageURI_Call) RunAndReturn(run func(ctx context.Context, component images.ComponentType, registry string) (string, error)) *Client_ComponentLatestImageURI_Call {
	_c.Call.Return(run)
	return _c
}
