// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube/logmonitoring"
	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube/metadataenrichment"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/settings"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIClient creates a new instance of APIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIClient {
	mock := &APIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

type APIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *APIClient) EXPECT() *APIClient_Expecter {
	return &APIClient_Expecter{mock: &_m.Mock}
}

// CreateKSPMSetting provides a mock function for the type APIClient
func (_mock *APIClient) CreateKSPMSetting(ctx context.Context, monitoredEntity string, datasetPipelineEnabled bool) (string, error) {
	ret := _mock.Called(ctx, monitoredEntity, datasetPipelineEnabled)

	if len(ret) == 0 {
		panic("no return value specified for CreateKSPMSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (string, error)); ok {
		return returnFunc(ctx, monitoredEntity, datasetPipelineEnabled)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) string); ok {
		r0 = returnFunc(ctx, monitoredEntity, datasetPipelineEnabled)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, monitoredEntity, datasetPipelineEnabled)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_CreateKSPMSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKSPMSetting'
type APIClient_CreateKSPMSetting_Call struct {
	*mock.Call
}

// CreateKSPMSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity string
//   - datasetPipelineEnabled bool
func (_e *APIClient_Expecter) CreateKSPMSetting(ctx interface{}, monitoredEntity interface{}, datasetPipelineEnabled interface{}) *APIClient_CreateKSPMSetting_Call {
	return &APIClient_CreateKSPMSetting_Call{Call: _e.mock.On("CreateKSPMSetting", ctx, monitoredEntity, datasetPipelineEnabled)}
}

func (_c *APIClient_CreateKSPMSetting_Call) Run(run func(ctx context.Context, monitoredEntity string, datasetPipelineEnabled bool)) *APIClient_CreateKSPMSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *APIClient_CreateKSPMSetting_Call) Return(s string, err error) *APIClient_CreateKSPMSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *APIClient_CreateKSPMSetting_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity string, datasetPipelineEnabled bool) (string, error)) *APIClient_CreateKSPMSetting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLogMonitoringSetting provides a mock function for the type APIClient
func (_mock *APIClient) CreateLogMonitoringSetting(ctx context.Context, scope string, clusterName string, matchers []logmonitoring.IngestRuleMatchers) (string, error) {
	ret := _mock.Called(ctx, scope, clusterName, matchers)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogMonitoringSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []logmonitoring.IngestRuleMatchers) (string, error)); ok {
		return returnFunc(ctx, scope, clusterName, matchers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []logmonitoring.IngestRuleMatchers) string); ok {
		r0 = returnFunc(ctx, scope, clusterName, matchers)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []logmonitoring.IngestRuleMatchers) error); ok {
		r1 = returnFunc(ctx, scope, clusterName, matchers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_CreateLogMonitoringSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLogMonitoringSetting'
type APIClient_CreateLogMonitoringSetting_Call struct {
	*mock.Call
}

// CreateLogMonitoringSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
//   - clusterName string
//   - matchers []logmonitoring.IngestRuleMatchers
func (_e *APIClient_Expecter) CreateLogMonitoringSetting(ctx interface{}, scope interface{}, clusterName interface{}, matchers interface{}) *APIClient_CreateLogMonitoringSetting_Call {
	return &APIClient_CreateLogMonitoringSetting_Call{Call: _e.mock.On("CreateLogMonitoringSetting", ctx, scope, clusterName, matchers)}
}

func (_c *APIClient_CreateLogMonitoringSetting_Call) Run(run func(ctx context.Context, scope string, clusterName string, matchers []logmonitoring.IngestRuleMatchers)) *APIClient_CreateLogMonitoringSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []logmonitoring.IngestRuleMatchers
		if args[3] != nil {
			arg3 = args[3].([]logmonitoring.IngestRuleMatchers)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *APIClient_CreateLogMonitoringSetting_Call) Return(s string, err error) *APIClient_CreateLogMonitoringSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *APIClient_CreateLogMonitoringSetting_Call) RunAndReturn(run func(ctx context.Context, scope string, clusterName string, matchers []logmonitoring.IngestRuleMatchers) (string, error)) *APIClient_CreateLogMonitoringSetting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateKubernetesAppSetting provides a mock function for the type APIClient
func (_mock *APIClient) CreateOrUpdateKubernetesAppSetting(ctx context.Context, scope string) (string, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateKubernetesAppSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_CreateOrUpdateKubernetesAppSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateKubernetesAppSetting'
type APIClient_CreateOrUpdateKubernetesAppSetting_Call struct {
	*mock.Call
}

// CreateOrUpdateKubernetesAppSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
func (_e *APIClient_Expecter) CreateOrUpdateKubernetesAppSetting(ctx interface{}, scope interface{}) *APIClient_CreateOrUpdateKubernetesAppSetting_Call {
	return &APIClient_CreateOrUpdateKubernetesAppSetting_Call{Call: _e.mock.On("CreateOrUpdateKubernetesAppSetting", ctx, scope)}
}

func (_c *APIClient_CreateOrUpdateKubernetesAppSetting_Call) Run(run func(ctx context.Context, scope string)) *APIClient_CreateOrUpdateKubernetesAppSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_CreateOrUpdateKubernetesAppSetting_Call) Return(s string, err error) *APIClient_CreateOrUpdateKubernetesAppSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *APIClient_CreateOrUpdateKubernetesAppSetting_Call) RunAndReturn(run func(ctx context.Context, scope string) (string, error)) *APIClient_CreateOrUpdateKubernetesAppSetting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateKubernetesSetting provides a mock function for the type APIClient
func (_mock *APIClient) CreateOrUpdateKubernetesSetting(ctx context.Context, clusterLabel string, kubeSystemUUID string, scope string) (string, error) {
	ret := _mock.Called(ctx, clusterLabel, kubeSystemUUID, scope)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateKubernetesSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, clusterLabel, kubeSystemUUID, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, clusterLabel, kubeSystemUUID, scope)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, clusterLabel, kubeSystemUUID, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_CreateOrUpdateKubernetesSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateKubernetesSetting'
type APIClient_CreateOrUpdateKubernetesSetting_Call struct {
	*mock.Call
}

// CreateOrUpdateKubernetesSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterLabel string
//   - kubeSystemUUID string
//   - scope string
func (_e *APIClient_Expecter) CreateOrUpdateKubernetesSetting(ctx interface{}, clusterLabel interface{}, kubeSystemUUID interface{}, scope interface{}) *APIClient_CreateOrUpdateKubernetesSetting_Call {
	return &APIClient_CreateOrUpdateKubernetesSetting_Call{Call: _e.mock.On("CreateOrUpdateKubernetesSetting", ctx, clusterLabel, kubeSystemUUID, scope)}
}

func (_c *APIClient_CreateOrUpdateKubernetesSetting_Call) Run(run func(ctx context.Context, clusterLabel string, kubeSystemUUID string, scope string)) *APIClient_CreateOrUpdateKubernetesSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *APIClient_CreateOrUpdateKubernetesSetting_Call) Return(s string, err error) *APIClient_CreateOrUpdateKubernetesSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *APIClient_CreateOrUpdateKubernetesSetting_Call) RunAndReturn(run func(ctx context.Context, clusterLabel string, kubeSystemUUID string, scope string) (string, error)) *APIClient_CreateOrUpdateKubernetesSetting_Call {
	_c.Call.Return(run)
	return _c
}

// GetK8sClusterME provides a mock function for the type APIClient
func (_mock *APIClient) GetK8sClusterME(ctx context.Context, kubeSystemUUID string) (settings.K8sClusterME, error) {
	ret := _mock.Called(ctx, kubeSystemUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetK8sClusterME")
	}

	var r0 settings.K8sClusterME
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (settings.K8sClusterME, error)); ok {
		return returnFunc(ctx, kubeSystemUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) settings.K8sClusterME); ok {
		r0 = returnFunc(ctx, kubeSystemUUID)
	} else {
		r0 = ret.Get(0).(settings.K8sClusterME)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, kubeSystemUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetK8sClusterME_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetK8sClusterME'
type APIClient_GetK8sClusterME_Call struct {
	*mock.Call
}

// GetK8sClusterME is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeSystemUUID string
func (_e *APIClient_Expecter) GetK8sClusterME(ctx interface{}, kubeSystemUUID interface{}) *APIClient_GetK8sClusterME_Call {
	return &APIClient_GetK8sClusterME_Call{Call: _e.mock.On("GetK8sClusterME", ctx, kubeSystemUUID)}
}

func (_c *APIClient_GetK8sClusterME_Call) Run(run func(ctx context.Context, kubeSystemUUID string)) *APIClient_GetK8sClusterME_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_GetK8sClusterME_Call) Return(k8sClusterME settings.K8sClusterME, err error) *APIClient_GetK8sClusterME_Call {
	_c.Call.Return(k8sClusterME, err)
	return _c
}

func (_c *APIClient_GetK8sClusterME_Call) RunAndReturn(run func(ctx context.Context, kubeSystemUUID string) (settings.K8sClusterME, error)) *APIClient_GetK8sClusterME_Call {
	_c.Call.Return(run)
	return _c
}

// GetKSPMSettings provides a mock function for the type APIClient
func (_mock *APIClient) GetKSPMSettings(ctx context.Context, monitoredEntity string) (settings.GetSettingsResponse, error) {
	ret := _mock.Called(ctx, monitoredEntity)

	if len(ret) == 0 {
		panic("no return value specified for GetKSPMSettings")
	}

	var r0 settings.GetSettingsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (settings.GetSettingsResponse, error)); ok {
		return returnFunc(ctx, monitoredEntity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) settings.GetSettingsResponse); ok {
		r0 = returnFunc(ctx, monitoredEntity)
	} else {
		r0 = ret.Get(0).(settings.GetSettingsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, monitoredEntity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetKSPMSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKSPMSettings'
type APIClient_GetKSPMSettings_Call struct {
	*mock.Call
}

// GetKSPMSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity string
func (_e *APIClient_Expecter) GetKSPMSettings(ctx interface{}, monitoredEntity interface{}) *APIClient_GetKSPMSettings_Call {
	return &APIClient_GetKSPMSettings_Call{Call: _e.mock.On("GetKSPMSettings", ctx, monitoredEntity)}
}

func (_c *APIClient_GetKSPMSettings_Call) Run(run func(ctx context.Context, monitoredEntity string)) *APIClient_GetKSPMSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_GetKSPMSettings_Call) Return(getSettingsResponse settings.GetSettingsResponse, err error) *APIClient_GetKSPMSettings_Call {
	_c.Call.Return(getSettingsResponse, err)
	return _c
}

func (_c *APIClient_GetKSPMSettings_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity string) (settings.GetSettingsResponse, error)) *APIClient_GetKSPMSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetRules provides a mock function for the type APIClient
func (_mock *APIClient) GetRules(ctx context.Context, kubeSystemUUID string, entityID string) ([]metadataenrichment.Rule, error) {
	ret := _mock.Called(ctx, kubeSystemUUID, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetRules")
	}

	var r0 []metadataenrichment.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]metadataenrichment.Rule, error)); ok {
		return returnFunc(ctx, kubeSystemUUID, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []metadataenrichment.Rule); ok {
		r0 = returnFunc(ctx, kubeSystemUUID, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metadataenrichment.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, kubeSystemUUID, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRules'
type APIClient_GetRules_Call struct {
	*mock.Call
}

// GetRules is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeSystemUUID string
//   - entityID string
func (_e *APIClient_Expecter) GetRules(ctx interface{}, kubeSystemUUID interface{}, entityID interface{}) *APIClient_GetRules_Call {
	return &APIClient_GetRules_Call{Call: _e.mock.On("GetRules", ctx, kubeSystemUUID, entityID)}
}

func (_c *APIClient_GetRules_Call) Run(run func(ctx context.Context, kubeSystemUUID string, entityID string)) *APIClient_GetRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *APIClient_GetRules_Call) Return(rules []metadataenrichment.Rule, err error) *APIClient_GetRules_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *APIClient_GetRules_Call) RunAndReturn(run func(ctx context.Context, kubeSystemUUID string, entityID string) ([]metadataenrichment.Rule, error)) *APIClient_GetRules_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettingsForLogModule provides a mock function for the type APIClient
func (_mock *APIClient) GetSettingsForLogModule(ctx context.Context, monitoredEntity string) (settings.GetSettingsResponse, error) {
	ret := _mock.Called(ctx, monitoredEntity)

	if len(ret) == 0 {
		panic("no return value specified for GetSettingsForLogModule")
	}

	var r0 settings.GetSettingsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (settings.GetSettingsResponse, error)); ok {
		return returnFunc(ctx, monitoredEntity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) settings.GetSettingsResponse); ok {
		r0 = returnFunc(ctx, monitoredEntity)
	} else {
		r0 = ret.Get(0).(settings.GetSettingsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, monitoredEntity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetSettingsForLogModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettingsForLogModule'
type APIClient_GetSettingsForLogModule_Call struct {
	*mock.Call
}

// GetSettingsForLogModule is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity string
func (_e *APIClient_Expecter) GetSettingsForLogModule(ctx interface{}, monitoredEntity interface{}) *APIClient_GetSettingsForLogModule_Call {
	return &APIClient_GetSettingsForLogModule_Call{Call: _e.mock.On("GetSettingsForLogModule", ctx, monitoredEntity)}
}

func (_c *APIClient_GetSettingsForLogModule_Call) Run(run func(ctx context.Context, monitoredEntity string)) *APIClient_GetSettingsForLogModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_GetSettingsForLogModule_Call) Return(getSettingsResponse settings.GetSettingsResponse, err error) *APIClient_GetSettingsForLogModule_Call {
	_c.Call.Return(getSettingsResponse, err)
	return _c
}

func (_c *APIClient_GetSettingsForLogModule_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity string) (settings.GetSettingsResponse, error)) *APIClient_GetSettingsForLogModule_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettingsForMonitoredEntity provides a mock function for the type APIClient
func (_mock *APIClient) GetSettingsForMonitoredEntity(ctx context.Context, monitoredEntity settings.K8sClusterME, schemaID string) (settings.GetSettingsResponse, error) {
	ret := _mock.Called(ctx, monitoredEntity, schemaID)

	if len(ret) == 0 {
		panic("no return value specified for GetSettingsForMonitoredEntity")
	}

	var r0 settings.GetSettingsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, settings.K8sClusterME, string) (settings.GetSettingsResponse, error)); ok {
		return returnFunc(ctx, monitoredEntity, schemaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, settings.K8sClusterME, string) settings.GetSettingsResponse); ok {
		r0 = returnFunc(ctx, monitoredEntity, schemaID)
	} else {
		r0 = ret.Get(0).(settings.GetSettingsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, settings.K8sClusterME, string) error); ok {
		r1 = returnFunc(ctx, monitoredEntity, schemaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetSettingsForMonitoredEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettingsForMonitoredEntity'
type APIClient_GetSettingsForMonitoredEntity_Call struct {
	*mock.Call
}

// GetSettingsForMonitoredEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity settings.K8sClusterME
//   - schemaID string
func (_e *APIClient_Expecter) GetSettingsForMonitoredEntity(ctx interface{}, monitoredEntity interface{}, schemaID interface{}) *APIClient_GetSettingsForMonitoredEntity_Call {
	return &APIClient_GetSettingsForMonitoredEntity_Call{Call: _e.mock.On("GetSettingsForMonitoredEntity", ctx, monitoredEntity, schemaID)}
}

func (_c *APIClient_GetSettingsForMonitoredEntity_Call) Run(run func(ctx context.Context, monitoredEntity settings.K8sClusterME, schemaID string)) *APIClient_GetSettingsForMonitoredEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 settings.K8sClusterME
		if args[1] != nil {
			arg1 = args[1].(settings.K8sClusterME)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *APIClient_GetSettingsForMonitoredEntity_Call) Return(getSettingsResponse settings.GetSettingsResponse, err error) *APIClient_GetSettingsForMonitoredEntity_Call {
	_c.Call.Return(getSettingsResponse, err)
	return _c
}

func (_c *APIClient_GetSettingsForMonitoredEntity_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity settings.K8sClusterME, schemaID string) (settings.GetSettingsResponse, error)) *APIClient_GetSettingsForMonitoredEntity_Call {
	_c.Call.Return(run)
	return _c
}
