// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube/logmonitoring"
	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube/metadataenrichment"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/settings"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CreateKSPMSetting provides a mock function for the type Client
func (_mock *Client) CreateKSPMSetting(ctx context.Context, monitoredEntity string, datasetPipelineEnabled bool) (string, error) {
	ret := _mock.Called(ctx, monitoredEntity, datasetPipelineEnabled)

	if len(ret) == 0 {
		panic("no return value specified for CreateKSPMSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (string, error)); ok {
		return returnFunc(ctx, monitoredEntity, datasetPipelineEnabled)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) string); ok {
		r0 = returnFunc(ctx, monitoredEntity, datasetPipelineEnabled)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, monitoredEntity, datasetPipelineEnabled)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_CreateKSPMSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKSPMSetting'
type Client_CreateKSPMSetting_Call struct {
	*mock.Call
}

// CreateKSPMSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity string
//   - datasetPipelineEnabled bool
func (_e *Client_Expecter) CreateKSPMSetting(ctx interface{}, monitoredEntity interface{}, datasetPipelineEnabled interface{}) *Client_CreateKSPMSetting_Call {
	return &Client_CreateKSPMSetting_Call{Call: _e.mock.On("CreateKSPMSetting", ctx, monitoredEntity, datasetPipelineEnabled)}
}

func (_c *Client_CreateKSPMSetting_Call) Run(run func(ctx context.Context, monitoredEntity string, datasetPipelineEnabled bool)) *Client_CreateKSPMSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_CreateKSPMSetting_Call) Return(s string, err error) *Client_CreateKSPMSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_CreateKSPMSetting_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity string, datasetPipelineEnabled bool) (string, error)) *Client_CreateKSPMSetting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLogMonitoringSetting provides a mock function for the type Client
func (_mock *Client) CreateLogMonitoringSetting(ctx context.Context, scope string, clusterName string, matchers []logmonitoring.IngestRuleMatchers) (string, error) {
	ret := _mock.Called(ctx, scope, clusterName, matchers)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogMonitoringSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []logmonitoring.IngestRuleMatchers) (string, error)); ok {
		return returnFunc(ctx, scope, clusterName, matchers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []logmonitoring.IngestRuleMatchers) string); ok {
		r0 = returnFunc(ctx, scope, clusterName, matchers)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []logmonitoring.IngestRuleMatchers) error); ok {
		r1 = returnFunc(ctx, scope, clusterName, matchers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_CreateLogMonitoringSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLogMonitoringSetting'
type Client_CreateLogMonitoringSetting_Call struct {
	*mock.Call
}

// CreateLogMonitoringSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
//   - clusterName string
//   - matchers []logmonitoring.IngestRuleMatchers
func (_e *Client_Expecter) CreateLogMonitoringSetting(ctx interface{}, scope interface{}, clusterName interface{}, matchers interface{}) *Client_CreateLogMonitoringSetting_Call {
	return &Client_CreateLogMonitoringSetting_Call{Call: _e.mock.On("CreateLogMonitoringSetting", ctx, scope, clusterName, matchers)}
}

func (_c *Client_CreateLogMonitoringSetting_Call) Run(run func(ctx context.Context, scope string, clusterName string, matchers []logmonitoring.IngestRuleMatchers)) *Client_CreateLogMonitoringSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []logmonitoring.IngestRuleMatchers
		if args[3] != nil {
			arg3 = args[3].([]logmonitoring.IngestRuleMatchers)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_CreateLogMonitoringSetting_Call) Return(s string, err error) *Client_CreateLogMonitoringSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_CreateLogMonitoringSetting_Call) RunAndReturn(run func(ctx context.Context, scope string, clusterName string, matchers []logmonitoring.IngestRuleMatchers) (string, error)) *Client_CreateLogMonitoringSetting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateKubernetesAppSetting provides a mock function for the type Client
func (_mock *Client) CreateOrUpdateKubernetesAppSetting(ctx context.Context, scope string) (string, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateKubernetesAppSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_CreateOrUpdateKubernetesAppSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateKubernetesAppSetting'
type Client_CreateOrUpdateKubernetesAppSetting_Call struct {
	*mock.Call
}

// CreateOrUpdateKubernetesAppSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
func (_e *Client_Expecter) CreateOrUpdateKubernetesAppSetting(ctx interface{}, scope interface{}) *Client_CreateOrUpdateKubernetesAppSetting_Call {
	return &Client_CreateOrUpdateKubernetesAppSetting_Call{Call: _e.mock.On("CreateOrUpdateKubernetesAppSetting", ctx, scope)}
}

func (_c *Client_CreateOrUpdateKubernetesAppSetting_Call) Run(run func(ctx context.Context, scope string)) *Client_CreateOrUpdateKubernetesAppSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_CreateOrUpdateKubernetesAppSetting_Call) Return(s string, err error) *Client_CreateOrUpdateKubernetesAppSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_CreateOrUpdateKubernetesAppSetting_Call) RunAndReturn(run func(ctx context.Context, scope string) (string, error)) *Client_CreateOrUpdateKubernetesAppSetting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateKubernetesSetting provides a mock function for the type Client
func (_mock *Client) CreateOrUpdateKubernetesSetting(ctx context.Context, clusterLabel string, kubeSystemUUID string, scope string) (string, error) {
	ret := _mock.Called(ctx, clusterLabel, kubeSystemUUID, scope)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateKubernetesSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, clusterLabel, kubeSystemUUID, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, clusterLabel, kubeSystemUUID, scope)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, clusterLabel, kubeSystemUUID, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_CreateOrUpdateKubernetesSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateKubernetesSetting'
type Client_CreateOrUpdateKubernetesSetting_Call struct {
	*mock.Call
}

// CreateOrUpdateKubernetesSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterLabel string
//   - kubeSystemUUID string
//   - scope string
func (_e *Client_Expecter) CreateOrUpdateKubernetesSetting(ctx interface{}, clusterLabel interface{}, kubeSystemUUID interface{}, scope interface{}) *Client_CreateOrUpdateKubernetesSetting_Call {
	return &Client_CreateOrUpdateKubernetesSetting_Call{Call: _e.mock.On("CreateOrUpdateKubernetesSetting", ctx, clusterLabel, kubeSystemUUID, scope)}
}

func (_c *Client_CreateOrUpdateKubernetesSetting_Call) Run(run func(ctx context.Context, clusterLabel string, kubeSystemUUID string, scope string)) *Client_CreateOrUpdateKubernetesSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_CreateOrUpdateKubernetesSetting_Call) Return(s string, err error) *Client_CreateOrUpdateKubernetesSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_CreateOrUpdateKubernetesSetting_Call) RunAndReturn(run func(ctx context.Context, clusterLabel string, kubeSystemUUID string, scope string) (string, error)) *Client_CreateOrUpdateKubernetesSetting_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSettings provides a mock function for the type Client
func (_mock *Client) DeleteSettings(ctx context.Context, settingsID string) error {
	ret := _mock.Called(ctx, settingsID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, settingsID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSettings'
type Client_DeleteSettings_Call struct {
	*mock.Call
}

// DeleteSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - settingsID string
func (_e *Client_Expecter) DeleteSettings(ctx interface{}, settingsID interface{}) *Client_DeleteSettings_Call {
	return &Client_DeleteSettings_Call{Call: _e.mock.On("DeleteSettings", ctx, settingsID)}
}

func (_c *Client_DeleteSettings_Call) Run(run func(ctx context.Context, settingsID string)) *Client_DeleteSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DeleteSettings_Call) Return(err error) *Client_DeleteSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteSettings_Call) RunAndReturn(run func(ctx context.Context, settingsID string) error) *Client_DeleteSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetK8sClusterME provides a mock function for the type Client
func (_mock *Client) GetK8sClusterME(ctx context.Context, kubeSystemUUID string) (settings.K8sClusterME, error) {
	ret := _mock.Called(ctx, kubeSystemUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetK8sClusterME")
	}

	var r0 settings.K8sClusterME
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (settings.K8sClusterME, error)); ok {
		return returnFunc(ctx, kubeSystemUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) settings.K8sClusterME); ok {
		r0 = returnFunc(ctx, kubeSystemUUID)
	} else {
		r0 = ret.Get(0).(settings.K8sClusterME)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, kubeSystemUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetK8sClusterME_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetK8sClusterME'
type Client_GetK8sClusterME_Call struct {
	*mock.Call
}

// GetK8sClusterME is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeSystemUUID string
func (_e *Client_Expecter) GetK8sClusterME(ctx interface{}, kubeSystemUUID interface{}) *Client_GetK8sClusterME_Call {
	return &Client_GetK8sClusterME_Call{Call: _e.mock.On("GetK8sClusterME", ctx, kubeSystemUUID)}
}

func (_c *Client_GetK8sClusterME_Call) Run(run func(ctx context.Context, kubeSystemUUID string)) *Client_GetK8sClusterME_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetK8sClusterME_Call) Return(k8sClusterME settings.K8sClusterME, err error) *Client_GetK8sClusterME_Call {
	_c.Call.Return(k8sClusterME, err)
	return _c
}

func (_c *Client_GetK8sClusterME_Call) RunAndReturn(run func(ctx context.Context, kubeSystemUUID string) (settings.K8sClusterME, error)) *Client_GetK8sClusterME_Call {
	_c.Call.Return(run)
	return _c
}

// GetKSPMSettings provides a mock function for the type Client
func (_mock *Client) GetKSPMSettings(ctx context.Context, monitoredEntity string) (settings.KSPMSettingsResponse, error) {
	ret := _mock.Called(ctx, monitoredEntity)

	if len(ret) == 0 {
		panic("no return value specified for GetKSPMSettings")
	}

	var r0 settings.KSPMSettingsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (settings.KSPMSettingsResponse, error)); ok {
		return returnFunc(ctx, monitoredEntity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) settings.KSPMSettingsResponse); ok {
		r0 = returnFunc(ctx, monitoredEntity)
	} else {
		r0 = ret.Get(0).(settings.KSPMSettingsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, monitoredEntity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetKSPMSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKSPMSettings'
type Client_GetKSPMSettings_Call struct {
	*mock.Call
}

// GetKSPMSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity string
func (_e *Client_Expecter) GetKSPMSettings(ctx interface{}, monitoredEntity interface{}) *Client_GetKSPMSettings_Call {
	return &Client_GetKSPMSettings_Call{Call: _e.mock.On("GetKSPMSettings", ctx, monitoredEntity)}
}

func (_c *Client_GetKSPMSettings_Call) Run(run func(ctx context.Context, monitoredEntity string)) *Client_GetKSPMSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetKSPMSettings_Call) Return(kSPMSettingsResponse settings.KSPMSettingsResponse, err error) *Client_GetKSPMSettings_Call {
	_c.Call.Return(kSPMSettingsResponse, err)
	return _c
}

func (_c *Client_GetKSPMSettings_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity string) (settings.KSPMSettingsResponse, error)) *Client_GetKSPMSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetRules provides a mock function for the type Client
func (_mock *Client) GetRules(ctx context.Context, kubeSystemUUID string, entityID string) ([]metadataenrichment.Rule, error) {
	ret := _mock.Called(ctx, kubeSystemUUID, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetRules")
	}

	var r0 []metadataenrichment.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]metadataenrichment.Rule, error)); ok {
		return returnFunc(ctx, kubeSystemUUID, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []metadataenrichment.Rule); ok {
		r0 = returnFunc(ctx, kubeSystemUUID, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metadataenrichment.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, kubeSystemUUID, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRules'
type Client_GetRules_Call struct {
	*mock.Call
}

// GetRules is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeSystemUUID string
//   - entityID string
func (_e *Client_Expecter) GetRules(ctx interface{}, kubeSystemUUID interface{}, entityID interface{}) *Client_GetRules_Call {
	return &Client_GetRules_Call{Call: _e.mock.On("GetRules", ctx, kubeSystemUUID, entityID)}
}

func (_c *Client_GetRules_Call) Run(run func(ctx context.Context, kubeSystemUUID string, entityID string)) *Client_GetRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetRules_Call) Return(rules []metadataenrichment.Rule, err error) *Client_GetRules_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *Client_GetRules_Call) RunAndReturn(run func(ctx context.Context, kubeSystemUUID string, entityID string) ([]metadataenrichment.Rule, error)) *Client_GetRules_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettingsForLogModule provides a mock function for the type Client
func (_mock *Client) GetSettingsForLogModule(ctx context.Context, monitoredEntity string) (settings.TotalCountSettingsResponse, error) {
	ret := _mock.Called(ctx, monitoredEntity)

	if len(ret) == 0 {
		panic("no return value specified for GetSettingsForLogModule")
	}

	var r0 settings.TotalCountSettingsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (settings.TotalCountSettingsResponse, error)); ok {
		return returnFunc(ctx, monitoredEntity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) settings.TotalCountSettingsResponse); ok {
		r0 = returnFunc(ctx, monitoredEntity)
	} else {
		r0 = ret.Get(0).(settings.TotalCountSettingsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, monitoredEntity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetSettingsForLogModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettingsForLogModule'
type Client_GetSettingsForLogModule_Call struct {
	*mock.Call
}

// GetSettingsForLogModule is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity string
func (_e *Client_Expecter) GetSettingsForLogModule(ctx interface{}, monitoredEntity interface{}) *Client_GetSettingsForLogModule_Call {
	return &Client_GetSettingsForLogModule_Call{Call: _e.mock.On("GetSettingsForLogModule", ctx, monitoredEntity)}
}

func (_c *Client_GetSettingsForLogModule_Call) Run(run func(ctx context.Context, monitoredEntity string)) *Client_GetSettingsForLogModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetSettingsForLogModule_Call) Return(totalCountSettingsResponse settings.TotalCountSettingsResponse, err error) *Client_GetSettingsForLogModule_Call {
	_c.Call.Return(totalCountSettingsResponse, err)
	return _c
}

func (_c *Client_GetSettingsForLogModule_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity string) (settings.TotalCountSettingsResponse, error)) *Client_GetSettingsForLogModule_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettingsForMonitoredEntity provides a mock function for the type Client
func (_mock *Client) GetSettingsForMonitoredEntity(ctx context.Context, monitoredEntity settings.K8sClusterME, schemaID string) (settings.TotalCountSettingsResponse, error) {
	ret := _mock.Called(ctx, monitoredEntity, schemaID)

	if len(ret) == 0 {
		panic("no return value specified for GetSettingsForMonitoredEntity")
	}

	var r0 settings.TotalCountSettingsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, settings.K8sClusterME, string) (settings.TotalCountSettingsResponse, error)); ok {
		return returnFunc(ctx, monitoredEntity, schemaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, settings.K8sClusterME, string) settings.TotalCountSettingsResponse); ok {
		r0 = returnFunc(ctx, monitoredEntity, schemaID)
	} else {
		r0 = ret.Get(0).(settings.TotalCountSettingsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, settings.K8sClusterME, string) error); ok {
		r1 = returnFunc(ctx, monitoredEntity, schemaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetSettingsForMonitoredEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettingsForMonitoredEntity'
type Client_GetSettingsForMonitoredEntity_Call struct {
	*mock.Call
}

// GetSettingsForMonitoredEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - monitoredEntity settings.K8sClusterME
//   - schemaID string
func (_e *Client_Expecter) GetSettingsForMonitoredEntity(ctx interface{}, monitoredEntity interface{}, schemaID interface{}) *Client_GetSettingsForMonitoredEntity_Call {
	return &Client_GetSettingsForMonitoredEntity_Call{Call: _e.mock.On("GetSettingsForMonitoredEntity", ctx, monitoredEntity, schemaID)}
}

func (_c *Client_GetSettingsForMonitoredEntity_Call) Run(run func(ctx context.Context, monitoredEntity settings.K8sClusterME, schemaID string)) *Client_GetSettingsForMonitoredEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 settings.K8sClusterME
		if args[1] != nil {
			arg1 = args[1].(settings.K8sClusterME)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetSettingsForMonitoredEntity_Call) Return(totalCountSettingsResponse settings.TotalCountSettingsResponse, err error) *Client_GetSettingsForMonitoredEntity_Call {
	_c.Call.Return(totalCountSettingsResponse, err)
	return _c
}

func (_c *Client_GetSettingsForMonitoredEntity_Call) RunAndReturn(run func(ctx context.Context, monitoredEntity settings.K8sClusterME, schemaID string) (settings.TotalCountSettingsResponse, error)) *Client_GetSettingsForMonitoredEntity_Call {
	_c.Call.Return(run)
	return _c
}
