// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/core"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// DELETE provides a mock function for the type Client
func (_mock *Client) DELETE(ctx context.Context, path string) core.Request {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DELETE")
	}

	var r0 core.Request
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) core.Request); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Request)
		}
	}
	return r0
}

// Client_DELETE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DELETE'
type Client_DELETE_Call struct {
	*mock.Call
}

// DELETE is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Client_Expecter) DELETE(ctx interface{}, path interface{}) *Client_DELETE_Call {
	return &Client_DELETE_Call{Call: _e.mock.On("DELETE", ctx, path)}
}

func (_c *Client_DELETE_Call) Run(run func(ctx context.Context, path string)) *Client_DELETE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DELETE_Call) Return(request core.Request) *Client_DELETE_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *Client_DELETE_Call) RunAndReturn(run func(ctx context.Context, path string) core.Request) *Client_DELETE_Call {
	_c.Call.Return(run)
	return _c
}

// GET provides a mock function for the type Client
func (_mock *Client) GET(ctx context.Context, path string) core.Request {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GET")
	}

	var r0 core.Request
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) core.Request); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Request)
		}
	}
	return r0
}

// Client_GET_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GET'
type Client_GET_Call struct {
	*mock.Call
}

// GET is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Client_Expecter) GET(ctx interface{}, path interface{}) *Client_GET_Call {
	return &Client_GET_Call{Call: _e.mock.On("GET", ctx, path)}
}

func (_c *Client_GET_Call) Run(run func(ctx context.Context, path string)) *Client_GET_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GET_Call) Return(request core.Request) *Client_GET_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *Client_GET_Call) RunAndReturn(run func(ctx context.Context, path string) core.Request) *Client_GET_Call {
	_c.Call.Return(run)
	return _c
}

// POST provides a mock function for the type Client
func (_mock *Client) POST(ctx context.Context, path string) core.Request {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for POST")
	}

	var r0 core.Request
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) core.Request); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Request)
		}
	}
	return r0
}

// Client_POST_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'POST'
type Client_POST_Call struct {
	*mock.Call
}

// POST is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Client_Expecter) POST(ctx interface{}, path interface{}) *Client_POST_Call {
	return &Client_POST_Call{Call: _e.mock.On("POST", ctx, path)}
}

func (_c *Client_POST_Call) Run(run func(ctx context.Context, path string)) *Client_POST_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_POST_Call) Return(request core.Request) *Client_POST_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *Client_POST_Call) RunAndReturn(run func(ctx context.Context, path string) core.Request) *Client_POST_Call {
	_c.Call.Return(run)
	return _c
}

// PUT provides a mock function for the type Client
func (_mock *Client) PUT(ctx context.Context, path string) core.Request {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for PUT")
	}

	var r0 core.Request
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) core.Request); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Request)
		}
	}
	return r0
}

// Client_PUT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PUT'
type Client_PUT_Call struct {
	*mock.Call
}

// PUT is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Client_Expecter) PUT(ctx interface{}, path interface{}) *Client_PUT_Call {
	return &Client_PUT_Call{Call: _e.mock.On("PUT", ctx, path)}
}

func (_c *Client_PUT_Call) Run(run func(ctx context.Context, path string)) *Client_PUT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_PUT_Call) Return(request core.Request) *Client_PUT_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *Client_PUT_Call) RunAndReturn(run func(ctx context.Context, path string) core.Request) *Client_PUT_Call {
	_c.Call.Return(run)
	return _c
}
