// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewInstaller creates a new instance of Installer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *Installer {
	mock := &Installer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Installer is an autogenerated mock type for the Installer type
type Installer struct {
	mock.Mock
}

type Installer_Expecter struct {
	mock *mock.Mock
}

func (_m *Installer) EXPECT() *Installer_Expecter {
	return &Installer_Expecter{mock: &_m.Mock}
}

// InstallAgent provides a mock function for the type Installer
func (_mock *Installer) InstallAgent(ctx context.Context, targetDir string) (bool, error) {
	ret := _mock.Called(ctx, targetDir)

	if len(ret) == 0 {
		panic("no return value specified for InstallAgent")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, targetDir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, targetDir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, targetDir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Installer_InstallAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallAgent'
type Installer_InstallAgent_Call struct {
	*mock.Call
}

// InstallAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - targetDir string
func (_e *Installer_Expecter) InstallAgent(ctx interface{}, targetDir interface{}) *Installer_InstallAgent_Call {
	return &Installer_InstallAgent_Call{Call: _e.mock.On("InstallAgent", ctx, targetDir)}
}

func (_c *Installer_InstallAgent_Call) Run(run func(ctx context.Context, targetDir string)) *Installer_InstallAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Installer_InstallAgent_Call) Return(b bool, err error) *Installer_InstallAgent_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Installer_InstallAgent_Call) RunAndReturn(run func(ctx context.Context, targetDir string) (bool, error)) *Installer_InstallAgent_Call {
	_c.Call.Return(run)
	return _c
}
