// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetLatestActiveGateVersion provides a mock function for the type Client
func (_mock *Client) GetLatestActiveGateVersion(ctx context.Context, os string) (string, error) {
	ret := _mock.Called(ctx, os)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestActiveGateVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, os)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, os)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, os)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetLatestActiveGateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestActiveGateVersion'
type Client_GetLatestActiveGateVersion_Call struct {
	*mock.Call
}

// GetLatestActiveGateVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - os string
func (_e *Client_Expecter) GetLatestActiveGateVersion(ctx interface{}, os interface{}) *Client_GetLatestActiveGateVersion_Call {
	return &Client_GetLatestActiveGateVersion_Call{Call: _e.mock.On("GetLatestActiveGateVersion", ctx, os)}
}

func (_c *Client_GetLatestActiveGateVersion_Call) Run(run func(ctx context.Context, os string)) *Client_GetLatestActiveGateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetLatestActiveGateVersion_Call) Return(s string, err error) *Client_GetLatestActiveGateVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_GetLatestActiveGateVersion_Call) RunAndReturn(run func(ctx context.Context, os string) (string, error)) *Client_GetLatestActiveGateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestAgentVersion provides a mock function for the type Client
func (_mock *Client) GetLatestAgentVersion(ctx context.Context, os string, installerType string) (string, error) {
	ret := _mock.Called(ctx, os, installerType)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestAgentVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, os, installerType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, os, installerType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, os, installerType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetLatestAgentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestAgentVersion'
type Client_GetLatestAgentVersion_Call struct {
	*mock.Call
}

// GetLatestAgentVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - os string
//   - installerType string
func (_e *Client_Expecter) GetLatestAgentVersion(ctx interface{}, os interface{}, installerType interface{}) *Client_GetLatestAgentVersion_Call {
	return &Client_GetLatestAgentVersion_Call{Call: _e.mock.On("GetLatestAgentVersion", ctx, os, installerType)}
}

func (_c *Client_GetLatestAgentVersion_Call) Run(run func(ctx context.Context, os string, installerType string)) *Client_GetLatestAgentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetLatestAgentVersion_Call) Return(s string, err error) *Client_GetLatestAgentVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_GetLatestAgentVersion_Call) RunAndReturn(run func(ctx context.Context, os string, installerType string) (string, error)) *Client_GetLatestAgentVersion_Call {
	_c.Call.Return(run)
	return _c
}
