// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/edgeconnect"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIClient creates a new instance of APIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIClient {
	mock := &APIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

type APIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *APIClient) EXPECT() *APIClient_Expecter {
	return &APIClient_Expecter{mock: &_m.Mock}
}

// CreateConnectionSetting provides a mock function for the type APIClient
func (_mock *APIClient) CreateConnectionSetting(ctx context.Context, es edgeconnect.EnvironmentSetting) error {
	ret := _mock.Called(ctx, es)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnectionSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, edgeconnect.EnvironmentSetting) error); ok {
		r0 = returnFunc(ctx, es)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_CreateConnectionSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnectionSetting'
type APIClient_CreateConnectionSetting_Call struct {
	*mock.Call
}

// CreateConnectionSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - es edgeconnect.EnvironmentSetting
func (_e *APIClient_Expecter) CreateConnectionSetting(ctx interface{}, es interface{}) *APIClient_CreateConnectionSetting_Call {
	return &APIClient_CreateConnectionSetting_Call{Call: _e.mock.On("CreateConnectionSetting", ctx, es)}
}

func (_c *APIClient_CreateConnectionSetting_Call) Run(run func(ctx context.Context, es edgeconnect.EnvironmentSetting)) *APIClient_CreateConnectionSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 edgeconnect.EnvironmentSetting
		if args[1] != nil {
			arg1 = args[1].(edgeconnect.EnvironmentSetting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_CreateConnectionSetting_Call) Return(err error) *APIClient_CreateConnectionSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_CreateConnectionSetting_Call) RunAndReturn(run func(ctx context.Context, es edgeconnect.EnvironmentSetting) error) *APIClient_CreateConnectionSetting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) CreateEdgeConnect(ctx context.Context, request *edgeconnect.Request) (edgeconnect.CreateResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateEdgeConnect")
	}

	var r0 edgeconnect.CreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *edgeconnect.Request) (edgeconnect.CreateResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *edgeconnect.Request) edgeconnect.CreateResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(edgeconnect.CreateResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *edgeconnect.Request) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_CreateEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEdgeConnect'
type APIClient_CreateEdgeConnect_Call struct {
	*mock.Call
}

// CreateEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - request *edgeconnect.Request
func (_e *APIClient_Expecter) CreateEdgeConnect(ctx interface{}, request interface{}) *APIClient_CreateEdgeConnect_Call {
	return &APIClient_CreateEdgeConnect_Call{Call: _e.mock.On("CreateEdgeConnect", ctx, request)}
}

func (_c *APIClient_CreateEdgeConnect_Call) Run(run func(ctx context.Context, request *edgeconnect.Request)) *APIClient_CreateEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *edgeconnect.Request
		if args[1] != nil {
			arg1 = args[1].(*edgeconnect.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_CreateEdgeConnect_Call) Return(createResponse edgeconnect.CreateResponse, err error) *APIClient_CreateEdgeConnect_Call {
	_c.Call.Return(createResponse, err)
	return _c
}

func (_c *APIClient_CreateEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, request *edgeconnect.Request) (edgeconnect.CreateResponse, error)) *APIClient_CreateEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConnectionSetting provides a mock function for the type APIClient
func (_mock *APIClient) DeleteConnectionSetting(ctx context.Context, objectID string) error {
	ret := _mock.Called(ctx, objectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnectionSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_DeleteConnectionSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnectionSetting'
type APIClient_DeleteConnectionSetting_Call struct {
	*mock.Call
}

// DeleteConnectionSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID string
func (_e *APIClient_Expecter) DeleteConnectionSetting(ctx interface{}, objectID interface{}) *APIClient_DeleteConnectionSetting_Call {
	return &APIClient_DeleteConnectionSetting_Call{Call: _e.mock.On("DeleteConnectionSetting", ctx, objectID)}
}

func (_c *APIClient_DeleteConnectionSetting_Call) Run(run func(ctx context.Context, objectID string)) *APIClient_DeleteConnectionSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_DeleteConnectionSetting_Call) Return(err error) *APIClient_DeleteConnectionSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_DeleteConnectionSetting_Call) RunAndReturn(run func(ctx context.Context, objectID string) error) *APIClient_DeleteConnectionSetting_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) DeleteEdgeConnect(ctx context.Context, edgeConnectID string) error {
	ret := _mock.Called(ctx, edgeConnectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEdgeConnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, edgeConnectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_DeleteEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEdgeConnect'
type APIClient_DeleteEdgeConnect_Call struct {
	*mock.Call
}

// DeleteEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - edgeConnectID string
func (_e *APIClient_Expecter) DeleteEdgeConnect(ctx interface{}, edgeConnectID interface{}) *APIClient_DeleteEdgeConnect_Call {
	return &APIClient_DeleteEdgeConnect_Call{Call: _e.mock.On("DeleteEdgeConnect", ctx, edgeConnectID)}
}

func (_c *APIClient_DeleteEdgeConnect_Call) Run(run func(ctx context.Context, edgeConnectID string)) *APIClient_DeleteEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_DeleteEdgeConnect_Call) Return(err error) *APIClient_DeleteEdgeConnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_DeleteEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, edgeConnectID string) error) *APIClient_DeleteEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionSettings provides a mock function for the type APIClient
func (_mock *APIClient) GetConnectionSettings(ctx context.Context) ([]edgeconnect.EnvironmentSetting, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionSettings")
	}

	var r0 []edgeconnect.EnvironmentSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]edgeconnect.EnvironmentSetting, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []edgeconnect.EnvironmentSetting); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgeconnect.EnvironmentSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetConnectionSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionSettings'
type APIClient_GetConnectionSettings_Call struct {
	*mock.Call
}

// GetConnectionSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *APIClient_Expecter) GetConnectionSettings(ctx interface{}) *APIClient_GetConnectionSettings_Call {
	return &APIClient_GetConnectionSettings_Call{Call: _e.mock.On("GetConnectionSettings", ctx)}
}

func (_c *APIClient_GetConnectionSettings_Call) Run(run func(ctx context.Context)) *APIClient_GetConnectionSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *APIClient_GetConnectionSettings_Call) Return(environmentSettings []edgeconnect.EnvironmentSetting, err error) *APIClient_GetConnectionSettings_Call {
	_c.Call.Return(environmentSettings, err)
	return _c
}

func (_c *APIClient_GetConnectionSettings_Call) RunAndReturn(run func(ctx context.Context) ([]edgeconnect.EnvironmentSetting, error)) *APIClient_GetConnectionSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) GetEdgeConnect(ctx context.Context, edgeConnectID string) (edgeconnect.GetResponse, error) {
	ret := _mock.Called(ctx, edgeConnectID)

	if len(ret) == 0 {
		panic("no return value specified for GetEdgeConnect")
	}

	var r0 edgeconnect.GetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (edgeconnect.GetResponse, error)); ok {
		return returnFunc(ctx, edgeConnectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) edgeconnect.GetResponse); ok {
		r0 = returnFunc(ctx, edgeConnectID)
	} else {
		r0 = ret.Get(0).(edgeconnect.GetResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, edgeConnectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEdgeConnect'
type APIClient_GetEdgeConnect_Call struct {
	*mock.Call
}

// GetEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - edgeConnectID string
func (_e *APIClient_Expecter) GetEdgeConnect(ctx interface{}, edgeConnectID interface{}) *APIClient_GetEdgeConnect_Call {
	return &APIClient_GetEdgeConnect_Call{Call: _e.mock.On("GetEdgeConnect", ctx, edgeConnectID)}
}

func (_c *APIClient_GetEdgeConnect_Call) Run(run func(ctx context.Context, edgeConnectID string)) *APIClient_GetEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_GetEdgeConnect_Call) Return(getResponse edgeconnect.GetResponse, err error) *APIClient_GetEdgeConnect_Call {
	_c.Call.Return(getResponse, err)
	return _c
}

func (_c *APIClient_GetEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, edgeConnectID string) (edgeconnect.GetResponse, error)) *APIClient_GetEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetEdgeConnects provides a mock function for the type APIClient
func (_mock *APIClient) GetEdgeConnects(ctx context.Context, name string) (edgeconnect.ListResponse, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetEdgeConnects")
	}

	var r0 edgeconnect.ListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (edgeconnect.ListResponse, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) edgeconnect.ListResponse); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(edgeconnect.ListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetEdgeConnects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEdgeConnects'
type APIClient_GetEdgeConnects_Call struct {
	*mock.Call
}

// GetEdgeConnects is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *APIClient_Expecter) GetEdgeConnects(ctx interface{}, name interface{}) *APIClient_GetEdgeConnects_Call {
	return &APIClient_GetEdgeConnects_Call{Call: _e.mock.On("GetEdgeConnects", ctx, name)}
}

func (_c *APIClient_GetEdgeConnects_Call) Run(run func(ctx context.Context, name string)) *APIClient_GetEdgeConnects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_GetEdgeConnects_Call) Return(listResponse edgeconnect.ListResponse, err error) *APIClient_GetEdgeConnects_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *APIClient_GetEdgeConnects_Call) RunAndReturn(run func(ctx context.Context, name string) (edgeconnect.ListResponse, error)) *APIClient_GetEdgeConnects_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnectionSetting provides a mock function for the type APIClient
func (_mock *APIClient) UpdateConnectionSetting(ctx context.Context, es edgeconnect.EnvironmentSetting) error {
	ret := _mock.Called(ctx, es)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnectionSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, edgeconnect.EnvironmentSetting) error); ok {
		r0 = returnFunc(ctx, es)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_UpdateConnectionSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnectionSetting'
type APIClient_UpdateConnectionSetting_Call struct {
	*mock.Call
}

// UpdateConnectionSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - es edgeconnect.EnvironmentSetting
func (_e *APIClient_Expecter) UpdateConnectionSetting(ctx interface{}, es interface{}) *APIClient_UpdateConnectionSetting_Call {
	return &APIClient_UpdateConnectionSetting_Call{Call: _e.mock.On("UpdateConnectionSetting", ctx, es)}
}

func (_c *APIClient_UpdateConnectionSetting_Call) Run(run func(ctx context.Context, es edgeconnect.EnvironmentSetting)) *APIClient_UpdateConnectionSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 edgeconnect.EnvironmentSetting
		if args[1] != nil {
			arg1 = args[1].(edgeconnect.EnvironmentSetting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_UpdateConnectionSetting_Call) Return(err error) *APIClient_UpdateConnectionSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_UpdateConnectionSetting_Call) RunAndReturn(run func(ctx context.Context, es edgeconnect.EnvironmentSetting) error) *APIClient_UpdateConnectionSetting_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) UpdateEdgeConnect(ctx context.Context, edgeConnectID string, request *edgeconnect.Request) error {
	ret := _mock.Called(ctx, edgeConnectID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEdgeConnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *edgeconnect.Request) error); ok {
		r0 = returnFunc(ctx, edgeConnectID, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_UpdateEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEdgeConnect'
type APIClient_UpdateEdgeConnect_Call struct {
	*mock.Call
}

// UpdateEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - edgeConnectID string
//   - request *edgeconnect.Request
func (_e *APIClient_Expecter) UpdateEdgeConnect(ctx interface{}, edgeConnectID interface{}, request interface{}) *APIClient_UpdateEdgeConnect_Call {
	return &APIClient_UpdateEdgeConnect_Call{Call: _e.mock.On("UpdateEdgeConnect", ctx, edgeConnectID, request)}
}

func (_c *APIClient_UpdateEdgeConnect_Call) Run(run func(ctx context.Context, edgeConnectID string, request *edgeconnect.Request)) *APIClient_UpdateEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *edgeconnect.Request
		if args[2] != nil {
			arg2 = args[2].(*edgeconnect.Request)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *APIClient_UpdateEdgeConnect_Call) Return(err error) *APIClient_UpdateEdgeConnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_UpdateEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, edgeConnectID string, request *edgeconnect.Request) error) *APIClient_UpdateEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}
