// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/edgeconnect"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIClient creates a new instance of APIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIClient {
	mock := &APIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

type APIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *APIClient) EXPECT() *APIClient_Expecter {
	return &APIClient_Expecter{mock: &_m.Mock}
}

// CreateEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) CreateEdgeConnect(ctx context.Context, request *edgeconnect.Request) (edgeconnect.APIResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateEdgeConnect")
	}

	var r0 edgeconnect.APIResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *edgeconnect.Request) (edgeconnect.APIResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *edgeconnect.Request) edgeconnect.APIResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(edgeconnect.APIResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *edgeconnect.Request) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_CreateEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEdgeConnect'
type APIClient_CreateEdgeConnect_Call struct {
	*mock.Call
}

// CreateEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - request *edgeconnect.Request
func (_e *APIClient_Expecter) CreateEdgeConnect(ctx interface{}, request interface{}) *APIClient_CreateEdgeConnect_Call {
	return &APIClient_CreateEdgeConnect_Call{Call: _e.mock.On("CreateEdgeConnect", ctx, request)}
}

func (_c *APIClient_CreateEdgeConnect_Call) Run(run func(ctx context.Context, request *edgeconnect.Request)) *APIClient_CreateEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *edgeconnect.Request
		if args[1] != nil {
			arg1 = args[1].(*edgeconnect.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_CreateEdgeConnect_Call) Return(aPIResponse edgeconnect.APIResponse, err error) *APIClient_CreateEdgeConnect_Call {
	_c.Call.Return(aPIResponse, err)
	return _c
}

func (_c *APIClient_CreateEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, request *edgeconnect.Request) (edgeconnect.APIResponse, error)) *APIClient_CreateEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEnvironmentSetting provides a mock function for the type APIClient
func (_mock *APIClient) CreateEnvironmentSetting(ctx context.Context, es edgeconnect.EnvironmentSetting) error {
	ret := _mock.Called(ctx, es)

	if len(ret) == 0 {
		panic("no return value specified for CreateEnvironmentSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, edgeconnect.EnvironmentSetting) error); ok {
		r0 = returnFunc(ctx, es)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_CreateEnvironmentSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEnvironmentSetting'
type APIClient_CreateEnvironmentSetting_Call struct {
	*mock.Call
}

// CreateEnvironmentSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - es edgeconnect.EnvironmentSetting
func (_e *APIClient_Expecter) CreateEnvironmentSetting(ctx interface{}, es interface{}) *APIClient_CreateEnvironmentSetting_Call {
	return &APIClient_CreateEnvironmentSetting_Call{Call: _e.mock.On("CreateEnvironmentSetting", ctx, es)}
}

func (_c *APIClient_CreateEnvironmentSetting_Call) Run(run func(ctx context.Context, es edgeconnect.EnvironmentSetting)) *APIClient_CreateEnvironmentSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 edgeconnect.EnvironmentSetting
		if args[1] != nil {
			arg1 = args[1].(edgeconnect.EnvironmentSetting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_CreateEnvironmentSetting_Call) Return(err error) *APIClient_CreateEnvironmentSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_CreateEnvironmentSetting_Call) RunAndReturn(run func(ctx context.Context, es edgeconnect.EnvironmentSetting) error) *APIClient_CreateEnvironmentSetting_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) DeleteEdgeConnect(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEdgeConnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_DeleteEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEdgeConnect'
type APIClient_DeleteEdgeConnect_Call struct {
	*mock.Call
}

// DeleteEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *APIClient_Expecter) DeleteEdgeConnect(ctx interface{}, id interface{}) *APIClient_DeleteEdgeConnect_Call {
	return &APIClient_DeleteEdgeConnect_Call{Call: _e.mock.On("DeleteEdgeConnect", ctx, id)}
}

func (_c *APIClient_DeleteEdgeConnect_Call) Run(run func(ctx context.Context, id string)) *APIClient_DeleteEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_DeleteEdgeConnect_Call) Return(err error) *APIClient_DeleteEdgeConnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_DeleteEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, id string) error) *APIClient_DeleteEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEnvironmentSetting provides a mock function for the type APIClient
func (_mock *APIClient) DeleteEnvironmentSetting(ctx context.Context, objectID string) error {
	ret := _mock.Called(ctx, objectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEnvironmentSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_DeleteEnvironmentSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEnvironmentSetting'
type APIClient_DeleteEnvironmentSetting_Call struct {
	*mock.Call
}

// DeleteEnvironmentSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID string
func (_e *APIClient_Expecter) DeleteEnvironmentSetting(ctx interface{}, objectID interface{}) *APIClient_DeleteEnvironmentSetting_Call {
	return &APIClient_DeleteEnvironmentSetting_Call{Call: _e.mock.On("DeleteEnvironmentSetting", ctx, objectID)}
}

func (_c *APIClient_DeleteEnvironmentSetting_Call) Run(run func(ctx context.Context, objectID string)) *APIClient_DeleteEnvironmentSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_DeleteEnvironmentSetting_Call) Return(err error) *APIClient_DeleteEnvironmentSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_DeleteEnvironmentSetting_Call) RunAndReturn(run func(ctx context.Context, objectID string) error) *APIClient_DeleteEnvironmentSetting_Call {
	_c.Call.Return(run)
	return _c
}

// GetEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) GetEdgeConnect(ctx context.Context, id string) (edgeconnect.APIResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEdgeConnect")
	}

	var r0 edgeconnect.APIResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (edgeconnect.APIResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) edgeconnect.APIResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(edgeconnect.APIResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_GetEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEdgeConnect'
type APIClient_GetEdgeConnect_Call struct {
	*mock.Call
}

// GetEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *APIClient_Expecter) GetEdgeConnect(ctx interface{}, id interface{}) *APIClient_GetEdgeConnect_Call {
	return &APIClient_GetEdgeConnect_Call{Call: _e.mock.On("GetEdgeConnect", ctx, id)}
}

func (_c *APIClient_GetEdgeConnect_Call) Run(run func(ctx context.Context, id string)) *APIClient_GetEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_GetEdgeConnect_Call) Return(aPIResponse edgeconnect.APIResponse, err error) *APIClient_GetEdgeConnect_Call {
	_c.Call.Return(aPIResponse, err)
	return _c
}

func (_c *APIClient_GetEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, id string) (edgeconnect.APIResponse, error)) *APIClient_GetEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}

// ListEdgeConnects provides a mock function for the type APIClient
func (_mock *APIClient) ListEdgeConnects(ctx context.Context, name string) ([]edgeconnect.APIResponse, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ListEdgeConnects")
	}

	var r0 []edgeconnect.APIResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]edgeconnect.APIResponse, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []edgeconnect.APIResponse); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgeconnect.APIResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_ListEdgeConnects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEdgeConnects'
type APIClient_ListEdgeConnects_Call struct {
	*mock.Call
}

// ListEdgeConnects is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *APIClient_Expecter) ListEdgeConnects(ctx interface{}, name interface{}) *APIClient_ListEdgeConnects_Call {
	return &APIClient_ListEdgeConnects_Call{Call: _e.mock.On("ListEdgeConnects", ctx, name)}
}

func (_c *APIClient_ListEdgeConnects_Call) Run(run func(ctx context.Context, name string)) *APIClient_ListEdgeConnects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_ListEdgeConnects_Call) Return(aPIResponses []edgeconnect.APIResponse, err error) *APIClient_ListEdgeConnects_Call {
	_c.Call.Return(aPIResponses, err)
	return _c
}

func (_c *APIClient_ListEdgeConnects_Call) RunAndReturn(run func(ctx context.Context, name string) ([]edgeconnect.APIResponse, error)) *APIClient_ListEdgeConnects_Call {
	_c.Call.Return(run)
	return _c
}

// ListEnvironmentSettings provides a mock function for the type APIClient
func (_mock *APIClient) ListEnvironmentSettings(ctx context.Context) ([]edgeconnect.EnvironmentSetting, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListEnvironmentSettings")
	}

	var r0 []edgeconnect.EnvironmentSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]edgeconnect.EnvironmentSetting, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []edgeconnect.EnvironmentSetting); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgeconnect.EnvironmentSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIClient_ListEnvironmentSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEnvironmentSettings'
type APIClient_ListEnvironmentSettings_Call struct {
	*mock.Call
}

// ListEnvironmentSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *APIClient_Expecter) ListEnvironmentSettings(ctx interface{}) *APIClient_ListEnvironmentSettings_Call {
	return &APIClient_ListEnvironmentSettings_Call{Call: _e.mock.On("ListEnvironmentSettings", ctx)}
}

func (_c *APIClient_ListEnvironmentSettings_Call) Run(run func(ctx context.Context)) *APIClient_ListEnvironmentSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *APIClient_ListEnvironmentSettings_Call) Return(environmentSettings []edgeconnect.EnvironmentSetting, err error) *APIClient_ListEnvironmentSettings_Call {
	_c.Call.Return(environmentSettings, err)
	return _c
}

func (_c *APIClient_ListEnvironmentSettings_Call) RunAndReturn(run func(ctx context.Context) ([]edgeconnect.EnvironmentSetting, error)) *APIClient_ListEnvironmentSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEdgeConnect provides a mock function for the type APIClient
func (_mock *APIClient) UpdateEdgeConnect(ctx context.Context, id string, request *edgeconnect.Request) error {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEdgeConnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *edgeconnect.Request) error); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_UpdateEdgeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEdgeConnect'
type APIClient_UpdateEdgeConnect_Call struct {
	*mock.Call
}

// UpdateEdgeConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request *edgeconnect.Request
func (_e *APIClient_Expecter) UpdateEdgeConnect(ctx interface{}, id interface{}, request interface{}) *APIClient_UpdateEdgeConnect_Call {
	return &APIClient_UpdateEdgeConnect_Call{Call: _e.mock.On("UpdateEdgeConnect", ctx, id, request)}
}

func (_c *APIClient_UpdateEdgeConnect_Call) Run(run func(ctx context.Context, id string, request *edgeconnect.Request)) *APIClient_UpdateEdgeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *edgeconnect.Request
		if args[2] != nil {
			arg2 = args[2].(*edgeconnect.Request)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *APIClient_UpdateEdgeConnect_Call) Return(err error) *APIClient_UpdateEdgeConnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_UpdateEdgeConnect_Call) RunAndReturn(run func(ctx context.Context, id string, request *edgeconnect.Request) error) *APIClient_UpdateEdgeConnect_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEnvironmentSetting provides a mock function for the type APIClient
func (_mock *APIClient) UpdateEnvironmentSetting(ctx context.Context, es edgeconnect.EnvironmentSetting) error {
	ret := _mock.Called(ctx, es)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEnvironmentSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, edgeconnect.EnvironmentSetting) error); ok {
		r0 = returnFunc(ctx, es)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// APIClient_UpdateEnvironmentSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEnvironmentSetting'
type APIClient_UpdateEnvironmentSetting_Call struct {
	*mock.Call
}

// UpdateEnvironmentSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - es edgeconnect.EnvironmentSetting
func (_e *APIClient_Expecter) UpdateEnvironmentSetting(ctx interface{}, es interface{}) *APIClient_UpdateEnvironmentSetting_Call {
	return &APIClient_UpdateEnvironmentSetting_Call{Call: _e.mock.On("UpdateEnvironmentSetting", ctx, es)}
}

func (_c *APIClient_UpdateEnvironmentSetting_Call) Run(run func(ctx context.Context, es edgeconnect.EnvironmentSetting)) *APIClient_UpdateEnvironmentSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 edgeconnect.EnvironmentSetting
		if args[1] != nil {
			arg1 = args[1].(edgeconnect.EnvironmentSetting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIClient_UpdateEnvironmentSetting_Call) Return(err error) *APIClient_UpdateEnvironmentSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *APIClient_UpdateEnvironmentSetting_Call) RunAndReturn(run func(ctx context.Context, es edgeconnect.EnvironmentSetting) error) *APIClient_UpdateEnvironmentSetting_Call {
	_c.Call.Return(run)
	return _c
}
