// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package injection

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube"
	mock "github.com/stretchr/testify/mock"
)

// newMockDynakubeReconciler creates a new instance of mockDynakubeReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDynakubeReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDynakubeReconciler {
	mock := &mockDynakubeReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDynakubeReconciler is an autogenerated mock type for the dynakubeReconciler type
type mockDynakubeReconciler struct {
	mock.Mock
}

type mockDynakubeReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDynakubeReconciler) EXPECT() *mockDynakubeReconciler_Expecter {
	return &mockDynakubeReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockDynakubeReconciler
func (_mock *mockDynakubeReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDynakubeReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockDynakubeReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockDynakubeReconciler_Expecter) Reconcile(ctx interface{}, dk interface{}) *mockDynakubeReconciler_Reconcile_Call {
	return &mockDynakubeReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk)}
}

func (_c *mockDynakubeReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockDynakubeReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDynakubeReconciler_Reconcile_Call) Return(err error) *mockDynakubeReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDynakubeReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockDynakubeReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
