{{- if .Values.rbac.oneAgent.create }}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-dynakube-oneagent
  namespace: {{ .Release.Namespace }}
  {{- if .Values.rbac.oneAgent.annotations }}
  annotations:
    {{- toYaml .Values.rbac.oneAgent.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dynatrace-operator.oneagentLabels" . | nindent 4 }}
automountServiceAccountToken: {{.Values.rbac.logMonitoring.create}}
{{ end }}
