{{- if (and .Values.rbac.extensions.prometheus.create .Values.rbac.extensions.create)}}
# Copyright Dynatrace LLC
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-extensions-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.openTelemetryCollectorLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - endpoints
      - services
      - nodes
      - nodes/metrics
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  {{- if (include "dynatrace-operator.openshiftOrOlm" .) }}
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
  {{ end }}
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-extensions-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.openTelemetryCollectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-extensions-prometheus
subjects:
  - kind: ServiceAccount
    name: dynatrace-otel-collector
    namespace: {{ .Release.Namespace }}
{{ end }}
