// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package activegate

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube"
	mock "github.com/stretchr/testify/mock"
)

// newMockIstioReconciler creates a new instance of mockIstioReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIstioReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIstioReconciler {
	mock := &mockIstioReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockIstioReconciler is an autogenerated mock type for the istioReconciler type
type mockIstioReconciler struct {
	mock.Mock
}

type mockIstioReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIstioReconciler) EXPECT() *mockIstioReconciler_Expecter {
	return &mockIstioReconciler_Expecter{mock: &_m.Mock}
}

// ReconcileActiveGate provides a mock function for the type mockIstioReconciler
func (_mock *mockIstioReconciler) ReconcileActiveGate(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileActiveGate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockIstioReconciler_ReconcileActiveGate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileActiveGate'
type mockIstioReconciler_ReconcileActiveGate_Call struct {
	*mock.Call
}

// ReconcileActiveGate is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockIstioReconciler_Expecter) ReconcileActiveGate(ctx interface{}, dk interface{}) *mockIstioReconciler_ReconcileActiveGate_Call {
	return &mockIstioReconciler_ReconcileActiveGate_Call{Call: _e.mock.On("ReconcileActiveGate", ctx, dk)}
}

func (_c *mockIstioReconciler_ReconcileActiveGate_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockIstioReconciler_ReconcileActiveGate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIstioReconciler_ReconcileActiveGate_Call) Return(err error) *mockIstioReconciler_ReconcileActiveGate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockIstioReconciler_ReconcileActiveGate_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockIstioReconciler_ReconcileActiveGate_Call {
	_c.Call.Return(run)
	return _c
}
