// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package activegate

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/activegate"
	"github.com/Dynatrace/dynatrace-operator/pkg/controllers/dynakube/token"
	mock "github.com/stretchr/testify/mock"
)

// newMockAuthTokenReconciler creates a new instance of mockAuthTokenReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthTokenReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthTokenReconciler {
	mock := &mockAuthTokenReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAuthTokenReconciler is an autogenerated mock type for the authTokenReconciler type
type mockAuthTokenReconciler struct {
	mock.Mock
}

type mockAuthTokenReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuthTokenReconciler) EXPECT() *mockAuthTokenReconciler_Expecter {
	return &mockAuthTokenReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockAuthTokenReconciler
func (_mock *mockAuthTokenReconciler) Reconcile(ctx context.Context, agClient activegate.APIClient, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, agClient, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, activegate.APIClient, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, agClient, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAuthTokenReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockAuthTokenReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - agClient activegate.APIClient
//   - dk *dynakube.DynaKube
func (_e *mockAuthTokenReconciler_Expecter) Reconcile(ctx interface{}, agClient interface{}, dk interface{}) *mockAuthTokenReconciler_Reconcile_Call {
	return &mockAuthTokenReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, agClient, dk)}
}

func (_c *mockAuthTokenReconciler_Reconcile_Call) Run(run func(ctx context.Context, agClient activegate.APIClient, dk *dynakube.DynaKube)) *mockAuthTokenReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 activegate.APIClient
		if args[1] != nil {
			arg1 = args[1].(activegate.APIClient)
		}
		var arg2 *dynakube.DynaKube
		if args[2] != nil {
			arg2 = args[2].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthTokenReconciler_Reconcile_Call) Return(err error) *mockAuthTokenReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAuthTokenReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, agClient activegate.APIClient, dk *dynakube.DynaKube) error) *mockAuthTokenReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIstioReconciler creates a new instance of mockIstioReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIstioReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIstioReconciler {
	mock := &mockIstioReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockIstioReconciler is an autogenerated mock type for the istioReconciler type
type mockIstioReconciler struct {
	mock.Mock
}

type mockIstioReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIstioReconciler) EXPECT() *mockIstioReconciler_Expecter {
	return &mockIstioReconciler_Expecter{mock: &_m.Mock}
}

// ReconcileActiveGate provides a mock function for the type mockIstioReconciler
func (_mock *mockIstioReconciler) ReconcileActiveGate(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileActiveGate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockIstioReconciler_ReconcileActiveGate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileActiveGate'
type mockIstioReconciler_ReconcileActiveGate_Call struct {
	*mock.Call
}

// ReconcileActiveGate is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockIstioReconciler_Expecter) ReconcileActiveGate(ctx interface{}, dk interface{}) *mockIstioReconciler_ReconcileActiveGate_Call {
	return &mockIstioReconciler_ReconcileActiveGate_Call{Call: _e.mock.On("ReconcileActiveGate", ctx, dk)}
}

func (_c *mockIstioReconciler_ReconcileActiveGate_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockIstioReconciler_ReconcileActiveGate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockIstioReconciler_ReconcileActiveGate_Call) Return(err error) *mockIstioReconciler_ReconcileActiveGate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockIstioReconciler_ReconcileActiveGate_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockIstioReconciler_ReconcileActiveGate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConnectionReconciler creates a new instance of mockConnectionReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConnectionReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConnectionReconciler {
	mock := &mockConnectionReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockConnectionReconciler is an autogenerated mock type for the connectionReconciler type
type mockConnectionReconciler struct {
	mock.Mock
}

type mockConnectionReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConnectionReconciler) EXPECT() *mockConnectionReconciler_Expecter {
	return &mockConnectionReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockConnectionReconciler
func (_mock *mockConnectionReconciler) Reconcile(ctx context.Context, agClient activegate.APIClient, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, agClient, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, activegate.APIClient, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, agClient, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnectionReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockConnectionReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - agClient activegate.APIClient
//   - dk *dynakube.DynaKube
func (_e *mockConnectionReconciler_Expecter) Reconcile(ctx interface{}, agClient interface{}, dk interface{}) *mockConnectionReconciler_Reconcile_Call {
	return &mockConnectionReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, agClient, dk)}
}

func (_c *mockConnectionReconciler_Reconcile_Call) Run(run func(ctx context.Context, agClient activegate.APIClient, dk *dynakube.DynaKube)) *mockConnectionReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 activegate.APIClient
		if args[1] != nil {
			arg1 = args[1].(activegate.APIClient)
		}
		var arg2 *dynakube.DynaKube
		if args[2] != nil {
			arg2 = args[2].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockConnectionReconciler_Reconcile_Call) Return(err error) *mockConnectionReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnectionReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, agClient activegate.APIClient, dk *dynakube.DynaKube) error) *mockConnectionReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPullSecretReconciler creates a new instance of mockPullSecretReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPullSecretReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPullSecretReconciler {
	mock := &mockPullSecretReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPullSecretReconciler is an autogenerated mock type for the pullSecretReconciler type
type mockPullSecretReconciler struct {
	mock.Mock
}

type mockPullSecretReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPullSecretReconciler) EXPECT() *mockPullSecretReconciler_Expecter {
	return &mockPullSecretReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockPullSecretReconciler
func (_mock *mockPullSecretReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube, tokens token.Tokens) error {
	ret := _mock.Called(ctx, dk, tokens)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube, token.Tokens) error); ok {
		r0 = returnFunc(ctx, dk, tokens)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPullSecretReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockPullSecretReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
//   - tokens token.Tokens
func (_e *mockPullSecretReconciler_Expecter) Reconcile(ctx interface{}, dk interface{}, tokens interface{}) *mockPullSecretReconciler_Reconcile_Call {
	return &mockPullSecretReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk, tokens)}
}

func (_c *mockPullSecretReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube, tokens token.Tokens)) *mockPullSecretReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		var arg2 token.Tokens
		if args[2] != nil {
			arg2 = args[2].(token.Tokens)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPullSecretReconciler_Reconcile_Call) Return(err error) *mockPullSecretReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPullSecretReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube, tokens token.Tokens) error) *mockPullSecretReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStatefulsetReconciler creates a new instance of mockStatefulsetReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStatefulsetReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStatefulsetReconciler {
	mock := &mockStatefulsetReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStatefulsetReconciler is an autogenerated mock type for the statefulsetReconciler type
type mockStatefulsetReconciler struct {
	mock.Mock
}

type mockStatefulsetReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStatefulsetReconciler) EXPECT() *mockStatefulsetReconciler_Expecter {
	return &mockStatefulsetReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockStatefulsetReconciler
func (_mock *mockStatefulsetReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStatefulsetReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockStatefulsetReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockStatefulsetReconciler_Expecter) Reconcile(ctx interface{}, dk interface{}) *mockStatefulsetReconciler_Reconcile_Call {
	return &mockStatefulsetReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk)}
}

func (_c *mockStatefulsetReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockStatefulsetReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockStatefulsetReconciler_Reconcile_Call) Return(err error) *mockStatefulsetReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStatefulsetReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockStatefulsetReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCapabilityReconciler creates a new instance of mockCapabilityReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCapabilityReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCapabilityReconciler {
	mock := &mockCapabilityReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockCapabilityReconciler is an autogenerated mock type for the capabilityReconciler type
type mockCapabilityReconciler struct {
	mock.Mock
}

type mockCapabilityReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCapabilityReconciler) EXPECT() *mockCapabilityReconciler_Expecter {
	return &mockCapabilityReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockCapabilityReconciler
func (_mock *mockCapabilityReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockCapabilityReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockCapabilityReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockCapabilityReconciler_Expecter) Reconcile(ctx interface{}, dk interface{}) *mockCapabilityReconciler_Reconcile_Call {
	return &mockCapabilityReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk)}
}

func (_c *mockCapabilityReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockCapabilityReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockCapabilityReconciler_Reconcile_Call) Return(err error) *mockCapabilityReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockCapabilityReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockCapabilityReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCustomPropertiesReconciler creates a new instance of mockCustomPropertiesReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCustomPropertiesReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCustomPropertiesReconciler {
	mock := &mockCustomPropertiesReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockCustomPropertiesReconciler is an autogenerated mock type for the customPropertiesReconciler type
type mockCustomPropertiesReconciler struct {
	mock.Mock
}

type mockCustomPropertiesReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCustomPropertiesReconciler) EXPECT() *mockCustomPropertiesReconciler_Expecter {
	return &mockCustomPropertiesReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockCustomPropertiesReconciler
func (_mock *mockCustomPropertiesReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockCustomPropertiesReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockCustomPropertiesReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockCustomPropertiesReconciler_Expecter) Reconcile(ctx interface{}, dk interface{}) *mockCustomPropertiesReconciler_Reconcile_Call {
	return &mockCustomPropertiesReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk)}
}

func (_c *mockCustomPropertiesReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockCustomPropertiesReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockCustomPropertiesReconciler_Reconcile_Call) Return(err error) *mockCustomPropertiesReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockCustomPropertiesReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockCustomPropertiesReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTlsReconciler creates a new instance of mockTlsReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTlsReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTlsReconciler {
	mock := &mockTlsReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockTlsReconciler is an autogenerated mock type for the tlsReconciler type
type mockTlsReconciler struct {
	mock.Mock
}

type mockTlsReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTlsReconciler) EXPECT() *mockTlsReconciler_Expecter {
	return &mockTlsReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockTlsReconciler
func (_mock *mockTlsReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockTlsReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockTlsReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
func (_e *mockTlsReconciler_Expecter) Reconcile(ctx interface{}, dk interface{}) *mockTlsReconciler_Reconcile_Call {
	return &mockTlsReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk)}
}

func (_c *mockTlsReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube)) *mockTlsReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockTlsReconciler_Reconcile_Call) Return(err error) *mockTlsReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockTlsReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube) error) *mockTlsReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
