name: Preflight
description: Does the preflight check
inputs:
  platforms:
    description: The platforms for which the image will be built
    default: linux/amd64,linux/arm64
    required: true
  images:
    description: Base names of the image tags
    required: false
  registry:
    description: The registry where the image is uploaded
    required: true
  repository:
    description: The repository in the registry where the image is uploaded
    required: true
  report-name:
    description: The name of the output report
    required: true
  redhat-project-id:
    description: The id for the redhat project.
    required: true
  pyxis-api-token:
    description: The pyxis api token
    required: true
  should-submit:
    description: Whether to submit the results to Red Hat
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
  - name: Sanitize names
    id: sanitize
    shell: bash
    run: |
      ref_name=$(hack/build/ci/sanitize-branch-name.sh "${{ github.ref_name }}")
      echo "ref_name=${ref_name}" >> $GITHUB_OUTPUT
      echo "ref_name_without_prefix=${ref_name#v}" >> $GITHUB_OUTPUT

      head_ref=$(hack/build/ci/sanitize-branch-name.sh "${{ github.head_ref }}")
      echo "head_ref=${head_ref}" >> $GITHUB_OUTPUT

      echo "ref_name=${ref_name}"
      echo "ref_name_without_prefix=${ref_name#v}"
      echo "head_ref=${head_ref}"
  - name: Set build date
    shell: bash
    id: set-build-date
    run: |
      echo "date=$(date --iso-8601)" >> $GITHUB_OUTPUT
  - name: Docker metadata
    uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
    id: meta
    env:
      DOCKER_METADATA_ANNOTATIONS_LEVELS: ${{ contains(inputs.platforms, ',') && 'manifest,index' || 'manifest' }}
    with:
      images: ${{ inputs.images }}
      tags: |
        # PRs
        # type=raw,value=snapshot-${{ github.head_ref }},enable=${{ github.event_name == 'pull_request' }}
        type=raw,value=snapshot-${{ steps.sanitize.outputs.head_ref }},enable=${{ github.event_name == 'pull_request' }}

        # main branches (not including nightly builds)
        type=raw,value=snapshot,enable=${{ github.ref_name == 'main' && github.event_name != 'schedule' }}

        # nightly builds
        type=raw,value=nightly-${{ steps.set-build-date.outputs.date }},enable=${{ github.event_name == 'schedule' }}
        type=raw,value=nightly,enable=${{ github.event_name == 'schedule' }}

        # tags
        # type=raw,value=${{ github.ref_name }},enable=${{ github.ref_type == 'tag' }}
        type=raw,value=${{ steps.sanitize.outputs.ref_name_without_prefix }},enable=${{ github.ref_type == 'tag' }}

        # all other branches including 'release-*' branches except 'main'
        # type=raw,value=${{ steps.prep.outputs.docker_image_tag_without_prefix }},enable=${{ !(github.event_name == 'pull_request' || github.ref_name == 'main' || github.ref_type == 'tag') }},priority=0
        type=raw,value=snapshot-${{ steps.sanitize.outputs.ref_name }},enable=${{ !(github.event_name == 'pull_request' || github.ref_name == 'main' || github.ref_type == 'tag') }},priority=0
  - name: Run preflight on image
    shell: bash
    env:
      RHCC_APITOKEN: ${{ inputs.pyxis-api-token }}
      RHCC_PROJECT_ID: ${{ inputs.redhat-project-id }}
      # renovate datasource=github-releases depName=redhat-openshift-ecosystem/openshift-preflight
      PREFLIGHT_VERSION: 1.15.2
      IMAGE_URI: ${{ inputs.registry }}/${{ inputs.repository }}:${{ steps.meta.outputs.tag-names }}
    run: |
      hack/build/ci/preflight.sh "${{ env.PREFLIGHT_VERSION }}" "${{ env.IMAGE_URI}}" "${{ inputs.report-name }}" "${{ inputs.should-submit }}"
  - name: Upload report
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
    with:
      name: preflight-report
      path: ${{ inputs.report-name }}
