// Copyright Dynatrace LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kubemon

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/activegate"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/image"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/version"
	"github.com/Dynatrace/dynatrace-operator/pkg/controllers/dynakube/token"
	mock "github.com/stretchr/testify/mock"
)

// newMockConnectionInfoReconciler creates a new instance of mockConnectionInfoReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConnectionInfoReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConnectionInfoReconciler {
	mock := &mockConnectionInfoReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockConnectionInfoReconciler is an autogenerated mock type for the connectionInfoReconciler type
type mockConnectionInfoReconciler struct {
	mock.Mock
}

type mockConnectionInfoReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConnectionInfoReconciler) EXPECT() *mockConnectionInfoReconciler_Expecter {
	return &mockConnectionInfoReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockConnectionInfoReconciler
func (_mock *mockConnectionInfoReconciler) Reconcile(ctx context.Context, agClient activegate.Client, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, agClient, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, activegate.Client, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, agClient, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnectionInfoReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockConnectionInfoReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - agClient activegate.Client
//   - dk *dynakube.DynaKube
func (_e *mockConnectionInfoReconciler_Expecter) Reconcile(ctx any, agClient any, dk any) *mockConnectionInfoReconciler_Reconcile_Call {
	return &mockConnectionInfoReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, agClient, dk)}
}

func (_c *mockConnectionInfoReconciler_Reconcile_Call) Run(run func(ctx context.Context, agClient activegate.Client, dk *dynakube.DynaKube)) *mockConnectionInfoReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 activegate.Client
		if args[1] != nil {
			arg1 = args[1].(activegate.Client)
		}
		var arg2 *dynakube.DynaKube
		if args[2] != nil {
			arg2 = args[2].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockConnectionInfoReconciler_Reconcile_Call) Return(err error) *mockConnectionInfoReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnectionInfoReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, agClient activegate.Client, dk *dynakube.DynaKube) error) *mockConnectionInfoReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAuthTokenReconciler creates a new instance of mockAuthTokenReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthTokenReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthTokenReconciler {
	mock := &mockAuthTokenReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAuthTokenReconciler is an autogenerated mock type for the authTokenReconciler type
type mockAuthTokenReconciler struct {
	mock.Mock
}

type mockAuthTokenReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuthTokenReconciler) EXPECT() *mockAuthTokenReconciler_Expecter {
	return &mockAuthTokenReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockAuthTokenReconciler
func (_mock *mockAuthTokenReconciler) Reconcile(ctx context.Context, agClient activegate.Client, dk *dynakube.DynaKube) error {
	ret := _mock.Called(ctx, agClient, dk)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, activegate.Client, *dynakube.DynaKube) error); ok {
		r0 = returnFunc(ctx, agClient, dk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAuthTokenReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockAuthTokenReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - agClient activegate.Client
//   - dk *dynakube.DynaKube
func (_e *mockAuthTokenReconciler_Expecter) Reconcile(ctx any, agClient any, dk any) *mockAuthTokenReconciler_Reconcile_Call {
	return &mockAuthTokenReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, agClient, dk)}
}

func (_c *mockAuthTokenReconciler_Reconcile_Call) Run(run func(ctx context.Context, agClient activegate.Client, dk *dynakube.DynaKube)) *mockAuthTokenReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 activegate.Client
		if args[1] != nil {
			arg1 = args[1].(activegate.Client)
		}
		var arg2 *dynakube.DynaKube
		if args[2] != nil {
			arg2 = args[2].(*dynakube.DynaKube)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthTokenReconciler_Reconcile_Call) Return(err error) *mockAuthTokenReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAuthTokenReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, agClient activegate.Client, dk *dynakube.DynaKube) error) *mockAuthTokenReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStatefulsetReconciler creates a new instance of mockStatefulsetReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStatefulsetReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStatefulsetReconciler {
	mock := &mockStatefulsetReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockStatefulsetReconciler is an autogenerated mock type for the statefulsetReconciler type
type mockStatefulsetReconciler struct {
	mock.Mock
}

type mockStatefulsetReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStatefulsetReconciler) EXPECT() *mockStatefulsetReconciler_Expecter {
	return &mockStatefulsetReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockStatefulsetReconciler
func (_mock *mockStatefulsetReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube, imageClient image.Client, versionClient version.Client) error {
	ret := _mock.Called(ctx, dk, imageClient, versionClient)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube, image.Client, version.Client) error); ok {
		r0 = returnFunc(ctx, dk, imageClient, versionClient)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockStatefulsetReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockStatefulsetReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
//   - imageClient image.Client
//   - versionClient version.Client
func (_e *mockStatefulsetReconciler_Expecter) Reconcile(ctx any, dk any, imageClient any, versionClient any) *mockStatefulsetReconciler_Reconcile_Call {
	return &mockStatefulsetReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk, imageClient, versionClient)}
}

func (_c *mockStatefulsetReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube, imageClient image.Client, versionClient version.Client)) *mockStatefulsetReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		var arg2 image.Client
		if args[2] != nil {
			arg2 = args[2].(image.Client)
		}
		var arg3 version.Client
		if args[3] != nil {
			arg3 = args[3].(version.Client)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockStatefulsetReconciler_Reconcile_Call) Return(err error) *mockStatefulsetReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockStatefulsetReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube, imageClient image.Client, versionClient version.Client) error) *mockStatefulsetReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPullSecretReconciler creates a new instance of mockPullSecretReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPullSecretReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPullSecretReconciler {
	mock := &mockPullSecretReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPullSecretReconciler is an autogenerated mock type for the pullSecretReconciler type
type mockPullSecretReconciler struct {
	mock.Mock
}

type mockPullSecretReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPullSecretReconciler) EXPECT() *mockPullSecretReconciler_Expecter {
	return &mockPullSecretReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockPullSecretReconciler
func (_mock *mockPullSecretReconciler) Reconcile(ctx context.Context, dk *dynakube.DynaKube, tokens token.Tokens) error {
	ret := _mock.Called(ctx, dk, tokens)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynakube.DynaKube, token.Tokens) error); ok {
		r0 = returnFunc(ctx, dk, tokens)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPullSecretReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockPullSecretReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dk *dynakube.DynaKube
//   - tokens token.Tokens
func (_e *mockPullSecretReconciler_Expecter) Reconcile(ctx any, dk any, tokens any) *mockPullSecretReconciler_Reconcile_Call {
	return &mockPullSecretReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dk, tokens)}
}

func (_c *mockPullSecretReconciler_Reconcile_Call) Run(run func(ctx context.Context, dk *dynakube.DynaKube, tokens token.Tokens)) *mockPullSecretReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynakube.DynaKube
		if args[1] != nil {
			arg1 = args[1].(*dynakube.DynaKube)
		}
		var arg2 token.Tokens
		if args[2] != nil {
			arg2 = args[2].(token.Tokens)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPullSecretReconciler_Reconcile_Call) Return(err error) *mockPullSecretReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPullSecretReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dk *dynakube.DynaKube, tokens token.Tokens) error) *mockPullSecretReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
