// Copyright Dynatrace LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dtprometheus

import (
	"context"

	"github.com/Dynatrace/dynatrace-operator/pkg/api/latest/dynakube"
	"github.com/Dynatrace/dynatrace-operator/pkg/api/v1alpha1/dtprometheus"
	"github.com/Dynatrace/dynatrace-operator/pkg/clients/dynatrace/image"
	mock "github.com/stretchr/testify/mock"
)

// newMockTargetAllocatorReconciler creates a new instance of mockTargetAllocatorReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTargetAllocatorReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTargetAllocatorReconciler {
	mock := &mockTargetAllocatorReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockTargetAllocatorReconciler is an autogenerated mock type for the targetAllocatorReconciler type
type mockTargetAllocatorReconciler struct {
	mock.Mock
}

type mockTargetAllocatorReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTargetAllocatorReconciler) EXPECT() *mockTargetAllocatorReconciler_Expecter {
	return &mockTargetAllocatorReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function for the type mockTargetAllocatorReconciler
func (_mock *mockTargetAllocatorReconciler) Reconcile(ctx context.Context, dtp *dtprometheus.DTPrometheus, dk *dynakube.DynaKube, imageClient image.Client) error {
	ret := _mock.Called(ctx, dtp, dk, imageClient)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dtprometheus.DTPrometheus, *dynakube.DynaKube, image.Client) error); ok {
		r0 = returnFunc(ctx, dtp, dk, imageClient)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockTargetAllocatorReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockTargetAllocatorReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - dtp *dtprometheus.DTPrometheus
//   - dk *dynakube.DynaKube
//   - imageClient image.Client
func (_e *mockTargetAllocatorReconciler_Expecter) Reconcile(ctx any, dtp any, dk any, imageClient any) *mockTargetAllocatorReconciler_Reconcile_Call {
	return &mockTargetAllocatorReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, dtp, dk, imageClient)}
}

func (_c *mockTargetAllocatorReconciler_Reconcile_Call) Run(run func(ctx context.Context, dtp *dtprometheus.DTPrometheus, dk *dynakube.DynaKube, imageClient image.Client)) *mockTargetAllocatorReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dtprometheus.DTPrometheus
		if args[1] != nil {
			arg1 = args[1].(*dtprometheus.DTPrometheus)
		}
		var arg2 *dynakube.DynaKube
		if args[2] != nil {
			arg2 = args[2].(*dynakube.DynaKube)
		}
		var arg3 image.Client
		if args[3] != nil {
			arg3 = args[3].(image.Client)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockTargetAllocatorReconciler_Reconcile_Call) Return(err error) *mockTargetAllocatorReconciler_Reconcile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockTargetAllocatorReconciler_Reconcile_Call) RunAndReturn(run func(ctx context.Context, dtp *dtprometheus.DTPrometheus, dk *dynakube.DynaKube, imageClient image.Client) error) *mockTargetAllocatorReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}
