// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	dynakube "github.com/Dynatrace/dynatrace-operator/src/api/v1beta1/dynakube"

	mock "github.com/stretchr/testify/mock"

	registry "github.com/Dynatrace/dynatrace-operator/src/registry"
)

// MockClientBuilder is an autogenerated mock type for the ClientBuilder type
type MockClientBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *MockClientBuilder) Build() (*registry.Client, error) {
	ret := _m.Called()

	var r0 *registry.Client
	var r1 error
	if rf, ok := ret.Get(0).(func() (*registry.Client, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *registry.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.Client)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetApiReader provides a mock function with given fields: _a0
func (_m *MockClientBuilder) SetApiReader(_a0 client.Reader) registry.ClientBuilder {
	ret := _m.Called(_a0)

	var r0 registry.ClientBuilder
	if rf, ok := ret.Get(0).(func(client.Reader) registry.ClientBuilder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(registry.ClientBuilder)
		}
	}

	return r0
}

// SetContext provides a mock function with given fields: _a0
func (_m *MockClientBuilder) SetContext(_a0 context.Context) registry.ClientBuilder {
	ret := _m.Called(_a0)

	var r0 registry.ClientBuilder
	if rf, ok := ret.Get(0).(func(context.Context) registry.ClientBuilder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(registry.ClientBuilder)
		}
	}

	return r0
}

// SetDynakube provides a mock function with given fields: _a0
func (_m *MockClientBuilder) SetDynakube(_a0 *dynakube.DynaKube) registry.ClientBuilder {
	ret := _m.Called(_a0)

	var r0 registry.ClientBuilder
	if rf, ok := ret.Get(0).(func(*dynakube.DynaKube) registry.ClientBuilder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(registry.ClientBuilder)
		}
	}

	return r0
}

// NewMockClientBuilder creates a new instance of MockClientBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientBuilder {
	mock := &MockClientBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
