name: OpenSSF Scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"
  push:
    branches:
      - main

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@PUT_FULL_SCORECARD_SHA_HERE # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@PUT_FULL_CODEQL_SHA_HERE # v3.x
        with:
          sarif_file: results.sarif

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@PUT_FULL_UPLOAD_ARTIFACT_SHA_HERE # v4.6.2
        with:
          name: OpenSSF Scorecard results
          path: results.sarif
          retention-days: 5
